---

# Status report
- name: Run status.sh
  become: yes
  shell: "{{ dir.script }}/status.sh"
- name: Set statefile
  set_fact:
    statefile: /etc/ansible/facts.d/state.yml
- name: Grant {{ statefile }} to user {{ user }}
  become: yes
  file: path={{ statefile }} owner={{ user }} group={{ user }}
- name: Load statefile
  include_vars: "{{ statefile }}"

- debug:
    var: configured
- debug:
    var: started

- shell: |
    echo "
    #######################################################################
    #                                                                     #
    #                     - Hitchwiki is installed -                      #
    #                                                                     #
    #                                                                     #
    # - Suspend the virtual machine by calling 'vagrant suspend'.         #
    # - When you're ready to begin working again, just run 'vagrant up'.  #
    # - To re-install, run 'vagrant destroy && vagrant up'.               #
    # - Read more at http://github.com/Hitchwiki/hitchwiki                #
    #                                                                     #
    #                 Have fun and happy hacking!                         #
    #                                                                     #
    #######################################################################
    Tip: Run 'rgrep TODO roles' to see open tasks."
  when: configured.system and configured.web and configured.db and configured.mw and configured.parsoid and started.apache and started.mysql and started.parsoid
  register: outro
- debug:
    var: outro.stdout_lines
  when: not outro|skipped

...
