---
# Status report

- name: Trigger status update
  shell: hostname
  register: hostname
  notify: status

- meta: flush_handlers

- set_fact:
    chapters:
    services:
    info: |
      #                                                                     #
      # - To connect run 'vagrant ssh'.                                     #
      # - Suspend the virtual machine by calling 'vagrant suspend'.         #
      # - When you're ready to begin working again, just run 'vagrant up'.  #
      # - Re-install VM: `cd scripts/vagrant; ./clean.sh; ./install.sh`     #
      #                                                                     #
      # - Read more about Hitchwiki development at                          #
      #    - https://github.com/Hitchwiki/hitchwiki/wiki and                #
      #    - https://github.com/Hitchwiki/hitchwiki/blob/master/INSTALL.md  #
      #                                                                     #

- name: Check chapters
  set_fact:
    chapters: "{{chapters}} {{item}}"
  when: configured[item]
  with_items: "{{configured}}"

- name: Check services
  set_fact:
    services: "{{services}} {{item}}"
  when: started[item]
  with_items: "{{started}}"

- name: Finished setup!
  when: configured.db and configured.web and configured.mw and started.apache and started.mysql
  register: finished
  set_fact:
    summary: |
      #######################################################################
      #                                                                     #
      #           - YAY! Hitchwiki installation is finished! -              #
      #                                                                     #
      # - Point your browser to {{ hostname.stdout }} or {{ ansible_host }}
      {{ info }}#                 Have fun and happy hacking!                         #
      #                                                                     #
      #######################################################################

         - Passed chapters: {{chapters}}
      
         - Started services: {{services}}
- name: Installation incomplete.
  when: finished|skipped
  set_fact:
    summary: |
      #######################################################################
      #                                                                     #
      #          The installation of Hitchwiki is not finished.             #
      #                                                                     #
      #######################################################################

         - Passed chapters: {{chapters}}
      
         - Started services: {{services}}

      #######################################################################
      #                                                                     #
      # - Please take some time to report the content of the file
      #   {{ dir.state }} to our ansible ticket at 
      #   https://github.com/Hitchwiki/hitchwiki/issues/172                 #
      {{ info }}#                 Good luck and have a nice day!                      #
      #                                                                     #
      #######################################################################
      
- name: Summary
  debug:
    msg: "{{ summary.split('\n') }}"
  when: no_outro is not defined

...
