---

# Status report
- set_fact:
    statefile: /etc/facts.d/state.yml
- file: state=absent path={{ statefile }}

- name: Check status
  become: yes
  shell: "{{ dir.script }}/status.sh"
  register: state
  ignore_errors: yes
- include_vars: "{{ statefile }}"

- debug: msg={{ item }}
  with_items: "cat {{myfile|quote}"

- shell: |
    echo "
    #######################################################################
    #                                                                     #
    #                     - Hitchwiki is installed -                      #
    #                                                                     #
    #                                                                     #
    # - Suspend the virtual machine by calling 'vagrant suspend'.         #
    # - When you're ready to begin working again, just run 'vagrant up'.  #
    # - To re-install, run 'vagrant destroy && vagrant up'.               #
    # - Read more at http://github.com/Hitchwiki/hitchwiki                #
    #                                                                     #
    #                 Have fun and happy hacking!                         #
    #                                                                     #
    #######################################################################
    Tip: Run 'rgrep TODO roles' to see open tasks."
  when: state.system and state.web and state.db and state.mw and state.parsoid (state.production or not env == 'production')
  register: outro
- debug:
    var: outro.stdout_lines

...
