---
# Status report

- name: Trigger status update
  shell: hostname
  register: hostname
  notify: status

- meta: flush_handlers

- set_fact:
    chapters:
    services:
    info: |
      #                                                                     #
      # - To connect run 'vagrant ssh'.                                     #
      # - Suspend the virtual machine by calling 'vagrant suspend'.         #
      # - When you're ready to begin working again, just run 'vagrant up'.  #
      # - Re-install VM: `cd scripts/vagrant; ./clean.sh; ./install.sh`     #
      #                                                                     #
      # - Read more about Hitchwiki development at                          #
      #    - https://github.com/Hitchwiki/hitchwiki/wiki and                #
      #    - https://github.com/Hitchwiki/hitchwiki/blob/master/INSTALL.md  #
      #                                                                     #

- name: Show finished chapters
  set_fact:
    chapters: "{{chapters}} {{item}}"
  when: configured[item]
  with_items: "{{configured}}"

- name: Show started services
  set_fact:
    services: "{{services}} {{item}}"
  when: started[item]
  with_items: "{{started}}"

- name: Finished setup!
  when: configured.db and configured.web and configured.mw and started.apache and started.mysql
  register: finished
  set_fact:
    summary: |
      #######################################################################
      #                                                                     #
      #                  - YAY! Hitchwiki is installed! -                   #
      #                                                                     #
      # - Point your browser to {{ hostname.stdout }} or {{ ansible_host }}
      {{ info }}#                 Have fun and happy hacking!                         #
      #                                                                     #
      #######################################################################

         - Passed chapters: {{chapters}}

         - Started services: {{services}}
- name: Installation incomplete.
  when: finished|skipped
  set_fact:
    summary: |
      #######################################################################
      #                                                                     #
      #          The installation of Hitchwiki is not finished.             #
      #                                                                     #
      # - Please report the content of the file {{ dir.state }}
      #   to our ansible ticket at
      #   https://github.com/Hitchwiki/hitchwiki/issues/172                 #
      {{ info }}#                 Good luck and have a nice day!                      #
      #                                                                     #
      #######################################################################

         - Passed chapters: {{chapters}}

         - Started services: {{services}}
      
- name: Summary
  debug:
    msg: "{{ summary.split('\n') }}"
  when: no_outro is not defined

# Network test
- name: Test https://localhost
  when: mediawiki.protocol == 'https' or env == 'production'
  uri: url=https://{{ item }} status_code=200,304
  with_items:
    - 127.0.0.1
    - "{{ domain }}"
  register: test_https
  ignore_errors: yes

- name: Test http://localhost
  uri: url=http://{{ item }} status_code=200,304
  with_items:
    - localhost
    - 127.0.0.1
    - "{{ hostvars.hostname }}"
    - "{{ ansible_host }}"
    - "{{ lookup('pipe', 'hostname') }}"
    - "{{ domain }}"
    - "{{ domain2 }}"
  register: test_http
  ignore_errors: yes

...
