---
# Prepare system to install hitchwiki

- name: Load settings
  include_vars: "{{ item }}"
  with_first_found:
    - configs/settings.yml
    - configs/settings-example.yml

- name: Prepare user
  include_tasks: user.yml
  tags: user

- name: Install dependencies
  include_tasks: user.yml
  tags: dependencies

- name: Check for /var/www/scripts
  stat: path=/var/www/scripts
  register: scripts_dir
  tags: repository

- name: Prepare repository
  when: not scripts_dir.stat.exists
  remote_user: "{{ user }}"
  include_tasks: repository.yml
  tags: repository

...
