---
# Run as root
- name: Does settings.yml exist?
  include_vars: configs/settings.yml

- name: Do we run inside vagrant?
  shell: "[ -d /var/www/configs ]"
  register: vagrant
  ignore_errors: yes

- name: Set root to /var/www
  set_fact:
    root: /var/www
    user: ubuntu
  when: vagrant|succeeded

- name: Prepare repository
  include_tasks: non-vagrant.yml
  when: vagrant|failed

- shell: "[ -f ~/.ssh/id_rsa ]"
  register: key_exists
  ignore_errors: yes
- name: Generate ssh key
  shell: ssh-keygen -qf ~/.ssh/id_rsa -P ""
  when: vagrant|succeeded and key_exists|failed

- shell: "[ -f /var/www/configs/authorized_keys ]"
  register: keys
  ignore_errors: yes
- name: Allow keys in `configs/authorized_keys` to connect as {{ user }}
  become: yes
  authorized_key: user={{ user }} state=present key="{{ lookup('file', 'configs/authorized_keys') }}"
  when: keys|succeeded

- name: Allow {{ user }} to connect without password
  # necessary for ansible to connect to localhost
  become: yes
  remote_user: "{{ user }}"
  shell: cat /home/{{ user }}/.ssh/id_rsa.pub >> /home/{{ user }}/.ssh/authorized_keys

- name: Use apt-cacher
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/apt-cacher-ng
    create: yes
    regexp: '^Acquire::http::Proxy'
    line: >
      Acquire::http::Proxy "http://{{ apt_proxy }}:3142/";
      Acquire::https::Proxy "false"; # or enable "PassThroughPattern: .*" in /etc/apt-cacher-ng/acng.conf
      # See https://blog.packagecloud.io/eng/2015/05/05/using-apt-cacher-ng-with-ssl-tls/
  when: apt_proxy is defined

- name: Install pip
  become: yes
  apt: name={{ item }} state=present
  with_items: { git, python-pip }

- name: Update pip and install ansible
  become: yes
  pip: name={{ item }} state=latest umask=0022
  with_items: { pip, ansible }

- name: Add '{{ domain }}' to `/etc/hosts`
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: 127.0.0.1 localhost {{ domain }}

- name: Change hostname to '{{ domain }}'
  become: yes
  hostname: name={{ domain }}

...
