---
# Prepare user
- debug: var=ansible_user

- name: Load settings
  include_vars: "{{ item }}"
  with_first_found:
    - configs/settings.yml
    - configs/settings-example.yml

- name: Add user {{ user }}
  become: yes
  user: generate_ssh_key=yes name={{ user }} uid=1050 shell=/bin/bash
  # https://docs.ansible.com/ansible/latest/user_module.html

- name: Add authorized_keys for {{ user }}
  when: "'travis' not in ansible_user"
  become: yes
  authorized_key: user={{ user }} state=present key="{{ lookup('file', item) }}"
  with_first_found:
    - configs/authorized_keys
    - ~/.ssh/id_rsa.pub
  register: add_ssh_key
  skip: true
- debug: msg="You won't be able to connect to this machine via ssh key. Did you run 'ssh-keygen'?"
  when: not add_ssh_key|succeeded

- name: Add {{ user }} to sudoers
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: '^{{user}}'
    line: "{{user}} ALL=NOPASSWD:ALL"

# Install dependencies
- name: Use apt-cacher
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/apt-cacher-ng
    create: yes
    regexp: '^Acquire::http::Proxy'
    line: >
      Acquire::http::Proxy "http://{{ apt_proxy }}:3142/";
      Acquire::https::Proxy "false"; # or enable "PassThroughPattern: .*" in /etc/apt-cacher-ng/acng.conf
      # See https://blog.packagecloud.io/eng/2015/05/05/using-apt-cacher-ng-with-ssl-tls/
  when: apt_proxy is defined

- name: Install git and pip
  become: yes
  apt: name={{ item }} state=present
  with_items: { git, python-pip }

- name: Update pip and install ansible
  become: yes
  pip: name={{ item }} state=latest umask=0022
  with_items: { pip, ansible }

# Prepare repository (non vagrant)
- name: Prepare repository
  when: ansible_user != "ubuntu" and ansible_user != "travis"
  remote_user: "{{ user }}"
  include_tasks: non-vagrant.yml

- set_fact: root={{ ansible_env.PWD }}/../../..
  when: ansible_user == "travis"
- name: Link {{ root }} to /var/www
  when: "'travis' not in ansible_user"
  file: state=link src={{ root }} path=/var/www owner={{ user }} group={{ user }}
  ignore_errors: yes

...
