---
# prepare repository when non run with vagrant

- name: Set root
  set_fact: root=/home/{{ user }}/src

- name: Does {{ root }} exist?
  shell: "[ -d {{ root }} ]"
  register: root_exists
  ignore_errors: yes

- name: Clone hitchwiki repository
  remote_user: "{{ user }}"
  git:
    dest: "{{ root }}"
    repo: https://github.com/traumschule/hitchwiki # TODO change later
    version: ansible
  when: root_exists|failed

- name: Link {{ root }} to /var/www
  file: state=link force=yes src={{ root }} path=/var/www owner={{ user }} group={{ user }}

- name: Copy settings.yml # from local to remote
  remote_user: "{{ user }}"
  copy: src={{ item }} dest={{ root }}/configs/settings.yml owner={{user}} group={{user}}
  with_first_found:
    - configs/settings.yml
    - configs/settings-example.yml

- name: Create ansible hosts file
  remote_user: "{{ user }}"
  lineinfile:
    path: "{{ root }}/scripts/ansible/hosts"
    owner: "{{ user }}"
    group: "{{ user }}"
    line: |
      [hitchwiki]
      localhost ansible_connection=local

...
