---
# syntax check: https://lint.travis-ci.org/

# Based on https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# and http://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/
# https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker
# https://www.jeffgeerling.com/blog/2017/fix-ansible-hanging-when-used-docker-and-tty

sudo: required # https://docs.travis-ci.com/user/reference/trusty

language: python
python: "2.7"

services:
  - docker

before_install:
  - docker run -d --name hitchwiki -v $(pwd):/var/www ubuntu:latest tail -f /dev/null # pull latest ubuntu LTS

install:
  - docker exec -t hitchwiki bash -c "apt-get update -qq &&
    apt-get install -y software-properties-common python-pip &&
    add-apt-repository universe && apt-get update -qq &&
    pip install --upgrade pip &&
    pip install ansible
    echo '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts"

script:
  - docker exec hitchwiki env ANSIBLE_FORCE_COLOR=1 ansible-playbook /var/www/scripts/ansible/tests/test.yml --syntax-check
  - docker exec hitchwiki env ANSIBLE_FORCE_COLOR=1 ansible-playbook /var/www/scripts/ansible/tests/test.yml
  - docker inspect -f {{.State.ExitCode}} hitchwiki
  - docker exec hitchwiki curl http://localhost
  - docker exec hitchwiki curl http://localhost:1080
