---
# syntax check: https://lint.travis-ci.org/

# Based on https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# and http://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/

sudo: required # https://docs.travis-ci.com/user/reference/trusty

# TODO enable when travis updated their chef scripts to support xenial (travis-ci/travis-ci#5821)
#dist: xenial # needed for php7 and composer

language: python
python: "2.7"

services:
  - docker

#addons:
#  mariadb: '10.0'

before_install:
  - docker run -d --name hitchwiki -v $(pwd):/var/www ubuntu:latest tail -f /dev/null # pull latest ubuntu LTS

install:
  - docker exec -t hitchwiki bash -c "apt-get update -qq &&
    apt-get install -y software-properties-common python-pip &&
    add-apt-repository universe && apt-get update -qq &&
    pip install --upgrade pip &&
    pip install ansible"

script:
  - docker exec -t hitchwiki bash -c "killall tail; cd /var/www/scripts/ansible &&
    ansible-playbook -i tests/inventory tests/test.yml --syntax-check &&
    ansible-playbook -i tests/inventory tests/test.yml --connection=local -b"
  - docker inspect -f {{.State.ExitCode}} hitchwiki
  - curl http://localhost
  - curl http://localhost:1080
  - curl http://localhost/phpmyadmin
