---
# syntax check: https://lint.travis-ci.org/

# Based on https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# and http://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/

sudo: required # https://docs.travis-ci.com/user/reference/trusty

# TODO enable when travis updated their chef scripts to support xenial (travis-ci/travis-ci#5821)
#dist: xenial # needed for php7 and composer

language: python
python: "2.7"

services:
  - docker

#addons:
#  mariadb: '10.0'

before_install:
  - docker run -d --name hitchwiki -v $(pwd):/travis ubuntu:latest tail -f /dev/null # pull latest ubuntu LTS
  - docker ps # show running containers

install:
  - docker exec -t hitchwiki bash -c "
    add-apt-repository universe;
    apt-get update -qq;
    apt-get install -y apache2 php-pear php-gettext php-xml php-json php7.0 php7.0-cli libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-gd php7.0-intl php7.0-imap php7.0-mcrypt php7.0-pspell php7.0-recode php7.0-sqlite3 php7.0-tidy php7.0-xmlrpc php7.0-xsl php7.0-mbstring php7.0-opcache;
    pip install ansible;
    cd scripts/ansible;
    export ANSIBLE_ROLES_PATH=$(pwd)/roles"

script:
  - docker exec -t hitchwiki bash -c "cd /travis;
    ansible-playbook -i tests/inventory tests/test.yml --syntax-check &&
    ansible-playbook -i tests/inventory tests/test.yml --connection=local -b &&
    curl http://localhost/"
