---
# syntax check: https://lint.travis-ci.org/
language: python
python: "2.7"
# python: "3" TODO test with ansible trunk
git:
  depth: 3
#branches:
#  except:
#  only:
#    - master
#    - testing
#    - idempotence

# Based on:
#  - https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
#  - http://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/
#  - https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker
#  - https://www.jeffgeerling.com/blog/2017/fix-ansible-hanging-when-used-docker-and-tty
#  - https://bertvv.github.io/notes-to-self/2015/12/13/testing-ansible-roles-with-travis-ci-part-2-multi-platform-tests/

sudo: required
#addons:
#  hosts:
#  - beta.hitchwiki.org

env:
  # Stable
  - os=ubuntu version=latest container_id=$(mktemp)
  #- os=debian version=latest container_id=$(mktemp)
  # Testing
  #- os=ubuntu version=rolling container_id=$(mktemp)
  #- os=debian version=testing container_id=$(mktemp)
  # Ubuntu: https://hub.docker.com/_/ubuntu/ - https://launchpad.net/ubuntu
  # Debian: https://hub.docker.com/_/debian/ - https://www.debian.org/releases/

matrix:
  fast_finish: true
  allow_failures:
    - env: os=debian
    - env: version=testing

before_install:
  - echo -e "CheckHostIP no\nStrictHostKeyChecking no" > ~/.ssh/config
  - ssh-keygen -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> configs/authorized_keys
  # pull and run prebuilt image
  - docker pull ${os}:${version}
  - docker run -d -h localhost --name "$(cat ${container_id})" -p 80:80 -p 5556:22 -v $(pwd):/var/www ${os}:${version} tail -f /dev/null > "${container_id}"

install:
  - > # prepare ansible
    docker exec "$(cat ${container_id})" bash -c 'apt-get update -qq &&
      apt-get install -qqy python-pip &&
      pip install --upgrade pip &&
      pip install ansible &&
      echo -e "[local]\nlocalhost ansible_connection=local" > /var/www/hosts'

before_script: # general settings
  - export ansible_command='cd /var/www/scripts/ansible && ansible-playbook hitchwiki.yml'

script: # run tests
  - docker exec "$(cat ${container_id})" bash -c "$ansible_command --syntax-check"
  - docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 bash -c "$ansible_command"
  #- docker exec "$(cat ${container_id})" bash -c 'sudo /var/www/scripts/clean_server.sh'
  #- ./scripts/deploy_remote.sh 127.0.0.1 5556 || 1

  - > # Idempotence test
    if [ "$TRAVIS_BRANCH" = "idempotence" ] ; then docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 bash -c "$ansible_command
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)"; fi

after_failure:
  - echo $TRAVIS_TEST_RESULT

#after_success:

#before_deploy:
#deploy:
#after_deploy:

after_script:
    # Clean up
  - sudo docker stop "$(cat ${container_id})"

notifications: # https://docs.travis-ci.com/user/notifications
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: "PecrOjfk/uTPWyRLDw0phN0N8h0IfyMaDX/t8Xwaav5/knqPVSp0nfokw9qsApSwLkRiUAtBtLlY7UHzj/v3S2eLtUG8/FoE9u3IDviWX845UD0FzeWV9gEC1LusblhFlJoE+325n5L2UkT141Uw2RJPB0Xk/QbvZuybpGfb3Fg="
  irc: 
    channels:
      - "chat.freenode.net#hitchhiking-dev"
    template:
      - "%{repository_slug}/%{commit} [%{build_number}:%{result}] %{message} (%{commit_subject}, %{author}) %{compare_url}"
    use_notice: true
