---
- name: Hitchwiki
# Ansible playbook for hitchwiki development environment
#   https://docs.ansible.com/ansible/latest/playbooks_intro.html
# Vagrant starts ansible after bringing up the machine (ubuntu/xenial)
#   https://docs.ansible.com/ansible/latest/guide_vagrant.html
#   https://www.vagrantup.com/docs/provisioning/ansible.html
# The user for the est environment is ubuntu. See Vagrantfile
  hosts: all
  remote_user: ubuntu
#  become: true
 
  # Ansible needs python or it fails with "/usr/bin/python: not found"
  # See https://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -yqq install python-simplejson

# Deployment is split into roles with tasks, handlers and templates:
#    https://docs.ansible.com/ansible/latest/playbooks_reuse.html
# 
# Following roles are based on the install_funcs.sh script by Pedro.
# Common is for system updates, db for mariadb, web for apache2, php and all modules, including composer, mw setups mediawiki and fills it.

- name: Common system configuration
  hosts: all
  roles:
    - common

- name: Deploy database server
  hosts: all
  roles:
    - db

- name: Setup webserver with PHP7 and node
  hosts: all
  roles:
    - web

- name: Install mediawiki, extensions and insert content
  hosts: all
  roles:
    - mw

# Production specific configuration
- name: Production
  hosts: all
  roles:
    - { role: production, when: env == "prod" }

# For development some services like mail-catcher and phpmyadmin are necessary.
- name: Development
  hosts: all
  roles:
    - { role: dev, when: env == "dev" }

...

# !unsafe https://docs.ansible.com/ansible/latest/playbooks_advanced_syntax.html
# local_home: "{{ lookup('env','HOME') }}" https://docs.ansible.com/ansible/latest/faq.html
# {{ ansible_env.SOME_VARIABLE }}
