---
# Ansible playbook for hitchwiki
#   https://docs.ansible.com/ansible/latest/playbooks_intro.html
# Vagrant starts ansible after bringing up the machine (ubuntu/xenial)
#   https://docs.ansible.com/ansible/latest/guide_vagrant.html
#   https://www.vagrantup.com/docs/provisioning/ansible.html
# Nice read: https://gitlab.com/osas/ansible-role-postgresql/blob/master/tasks/main.yml#L3

- hosts: all
  gather_facts: no

  pre_tasks:
    - import_tasks: roles/hitchwiki/tasks/system.yml
      when: finished_common_tasks is undefined or not finished_common_tasks

# Deployment is split into roles with tasks, handlers and templates:
#    https://docs.ansible.com/ansible/latest/playbooks_reuse.html
# 
# Following roles are 

- name: Setup hitchwiki
  hosts: all
  roles:
    - hitchwiki

...
