---
# Ansible playbook for hitchwiki
#   https://docs.ansible.com/ansible/latest/playbooks_intro.html
# Vagrant starts ansible after bringing up the machine (ubuntu/xenial)
#   https://docs.ansible.com/ansible/latest/guide_vagrant.html
#   https://www.vagrantup.com/docs/provisioning/ansible.html
# Nice read: https://gitlab.com/osas/ansible-role-postgresql/blob/master/tasks/main.yml#L3

- hosts: all
  gather_facts: no

  pre_tasks:
    - name: Prepare system
      include_tasks: roles/hitchwiki/tasks/system.yml
      when: not state_system or state_system is undefined

- name: Setup hitchwiki
  hosts: all
  roles:
    - hitchwiki

...
