---
# Playbook to test content migration to hitchwiki v3
# https://github.com/Hitchwiki/hitchwiki/labels/migrate

- hosts: all
  gather_facts: no

- name: Migrate content
  hosts: all
  roles:
    - migrate

...
