---
# Hitchwiki handlers

- name: Refresh status
  become: yes
  command: "{{ dir.script }}/status.sh"
  listen:
    - save
    - status
  notify:
    - fetch status
    - load
- name: Retrieve summary
  fetch: src={{ dir.state }} dest=status/{{ ansible_host }}/ flat=yes
  listen: "fetch status"
  notify: "load"
- name: Load variables
  include_vars: "status/{{ ansible_host }}/state.yml"
  listen:
    - load
    - reload

# System
- name: Update system
  become: yes
  apt: update_cache=yes upgrade=dist autoremove=yes autoclean=yes allow_unauthenticated=yes
  listen:
    - apt
    - update system

- name: Start monit
  become: yes
  service: name=monit state=restarted
  listen:
    - start monit
    - restart monit

# Database
- name: restart db
  become: yes
  service: name=mariadb state=restarted
  notify: "start db"

- name: start db
  become: yes
  service: name=mariadb state=started

# Webserver
- name: Restart apache
  become: yes
  service: name=apache2 state=restarted
  register: apache_restart
  listen:
    - apache
    - restart apache
    - apache2
    - restart apache2
    - webserver
    - restart webserver

# Mediawiki handlers
- name: Restart Parsoid
  become: yes
  service: name=parsoid state=started
  listen:
    - parsoid
    - restart parsoid

# Development environment
- name: Start maildev
  become: yes
  command: maildev --smtp 1025 --silent &
  listen:
    - maildev

- name: Stop maildev
  become: yes
  shell: kill $(pidof node /usr/local/bin/maildev)
  when: started.maildev
  ignore_errors: yes
  listen:
    - stop maildev

- name: Show databases
  command: IFS=$'\n' echo "SHOW DATABASES;" | mysql {{ db_credentials }} | grep -E '^hitchwiki_en' | sed 's/^hitchwiki_//g'
  register: tables
  listen:
    - languages
    - databases
- debug:
    var: tables.stdout

...
