---
# Productive environment

- name: Transport Layer Security (setup_ssl)
  include_tasks: setup_ssl.yml
  when: setup_ssl

# Monit
#- name: Clone into Monit 
#  git: repo: git clone=https://tildeslash@bitbucket.org/tildeslash/monit.git dest=~/moniit depth=1

#- name: Install monit dependencies
#  apt: name={{item}} state=present
#  with_items: { automake bison byacc flex libpam0g-dev } # libtool m4

#- name: Build monit
#  shell: |
#    cd ~/monit
#    ./configure
#    make

#- name: Install monit
#  become: yes
#  shell: cd /home/{{ ansible_user_id }}/monit; make install
- name: Install monit
  apt: name=monit state=present

- name: Monitor services
  monit: name={{item}} state=started
  # https://docs.ansible.com/ansible/latest/monit_module.html
  # https://mmonit.com/monit/documentation/monit.html
  with_items:
    - apache2
    - mariadb


    - 
# TODO untested

- name: Finish installation
  lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_installation'
    line: 'finished_installation: True'
  when: finished_common_tasks and finished_db_tasks and finished_web_tasks and finished_mw_tasks
  notify: status

...
