---
# Productive environment

# TODO use https://docs.ansible.com/ansible/latest/letsencrypt_module.html
# Check https://letsencrypt.org/2017/10/17/acme-support-in-apache-httpd.html
- name: Setup self signed SSL certificate
  shell: |
    cd {{ROOTDIR}}
    if [[ $* == *--ssl* ]]; then
      bash {{SCRIPTDIR}}/cert_selfsigned.sh
    else
      msg "Skipped installing self signed SSL certificate."
    fi
  when: setup_ssl

- name: Finish installation
  lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_installation'
    line: 'finished_installation: True'
  when: finished_common_tasks and finished_db_tasks and finished_web_tasks and finished_mw_tasks
  notify: status

...
