# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/src

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            #if [ "$CIRCLE_BRANCH" = 'testing' ] || [ "$CIRCLE_BRANCH" = 'idempotence' ] 
            #then exit 0 ; fi
            . venv/bin/activate
            cd scripts/ansible
            ansible-playbook tests/test.yml --syntax-check
            ansible-playbook tests/test.yml

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
