---
# Handlers for the development environment

- include_tasks: roles/db/handlers/main.yml
- include_tasks: roles/web/handlers/main.yml

- name: restart maildev
  become: yes
  service: name=maildev enabled=yes state=started
  tags:
    - mail
    - smptp
    - maildev

...
