---
# Handlers for the webservers

- name: restart apache
  become: yes
  service: name=apache2 state=restarted
  tags:
    - apache
    - apache2
    - web
    - webserver
    - phpmyadmin
    - mediawiki

# TODO fatal: [hitchwiki]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service apache2: Failed to restart apache2.service: Interactive authentication required.\nSee system logs and 'systemctl status apache2.service' for details.\n"}

...
