---
# Handlers for the webservers

- name: restart apache
  become: yes
  service: name=apache2 state=restarted
  tags:
    - apache
    - apache2
    - web
    - webserver
    - phpmyadmin
    - mediawiki

...
