---
# Hitchwiki handlers

- name: load
  include_vars: group_vars/all
  listen:
    - reload

# System
- name: Update system
  become: yes
  apt: update_cache=yes upgrade=dist autoremove=yes autoclean=yes
  listen:
    - apt
    - update system

# Database
- name: Restart mysql
  become: yes
  service: name=mariadb state=restarted
  listen:
    - database
    - mariadb
    - mysql
    - restart mysql
    - restart mariadb
    - restart dbserver

# Webserver
- name: Restart apache
  become: yes
  service: name=apache2 state=restarted
  register: apache_restart
  listen:
    - apache
    - restart apache
    - apache2
    - restart apache2
    - webserver
    - restart webserver

- debug:
    var: apache_restart.stderr_lines

- lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  web'
    line: '  web: True'
  when: apache_restart|succeeded
  notify:
  - load
- lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  web'
    line: '  web: False'
  when: apache_restart|failed
  notify:
  - load

# Mediawiki handlers
- name: Restart Parsoid
  become: yes
  monit: name=parsoid state=restarted
  listen:
    - parsoid
    - restart parsoid

# Development environment
- name: Start maildev
  become: yes
  command: maildev --smtp 1025 --silent
  #service: name=maildev enabled=yes state=started
  listen:
    - maildev

- name: Show databases
  command: IFS=$'\n' echo "SHOW DATABASES;" | mysql {{ db_credentials }} | grep -E '^hitchwiki_en' | sed 's/^hitchwiki_//g'
  register: tables
  listen:
    - languages
    - databases
- debug:
    var: tables.stdout

...
