---
# Hitchwiki handlers

# System
- name: Update system
  become: yes
  apt: update_cache=yes upgrade=dist autoremove=yes autoclean=yes
  listen: update system

# Database

- name: restart db
  become: yes
  service: name={{db.server}} enabled=yes state=restarted
  tags:
    - mariadb
    - db
    - dbserver
    - database

# Webserver

- name: restart apache
  become: yes
  service: name=apache2 state=restarted
  register: apache_restart
  tags:
    - apache
    - apache2
    - web
    - webserver
    - phpmyadmin
    - mediawiki

- debug:
    var: apache_restart.stderr_lines

- lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_web_tasks'
    line: 'finished_web_tasks: True'
  when: apache_restart|succeeded

- lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_web_tasks'
    line: 'finished_web_tasks: False'
  when: apache_restart|failed

# Mediawiki handlers
- name: Restart Parsoid
  service: name=parsoid state=restarted
  listen:
    - restart parsoid
  tags:
    - parsoid

# Development environment
- name: restart maildev
  become: yes
  service: name=maildev enabled=yes state=started
  tags:
    - mail
    - smptp
    - maildev

...
