---
# Hitchwiki handlers

- name: load
  include_vars: group_vars/all

# System
- name: Update system
  become: yes
  apt: update_cache=yes upgrade=dist autoremove=yes autoclean=yes
  listen: apt

# Database
- name: Restart database server
  become: yes
  service: name={{db.server}} enabled=yes state=restarted
  listen: database

# Webserver
- name: Restart apache
  become: yes
  service: name=apache2 state=restarted
  register: apache_restart
  listen: apache

- debug:
    var: apache_restart.stderr_lines

- lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  web'
    line: '  web: True'
  when: apache_restart|succeeded
  notify:
  - load
- lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  web'
    line: '  web: False'
  when: apache_restart|failed
  notify:
  - load

# Mediawiki handlers
- name: Restart Parsoid
  service: name=parsoid state=restarted
  listen: parsoid

# Development environment
- name: Start maildev
  become: yes
  command: maildev --smtp 1025 --silent
  #service: name=maildev enabled=yes state=started
  #systemd: name=maildev enabled=yes state=started
  listen: maildev

...
