---
# Devlopment specific tasks

- name: Transport Layer Security (setup_ssl)
  include_tasks: setup_ssl.yml
  when: setup_ssl

# Maildev
- name: Install PHP PEAR modules
  become: true
  pear: name={{item}} state=present
  with_items: { Auth_SASL, mail, mail_mime, Net_SMTP }

- name: Install Maildev for catching emails while developing
  become: true
  npm: name=maildev version=1.0.0-rc3 state=present global=yes
  notify: restart maildev

- name: Setup Maildev to start on reboot
  become: true
  file: state=link src={{ dir.script }}/init_maildev.sh path=/etc/init.d/maildev mode='755'

- name: Create Maildev startup symlink
  # TODO insserv Script maildev is broken incomplete LSB comment.
  become: true
  file: state=link src=/etc/init.d/maildev path=/etc/rc3.d/S99maildev

# PHPMyAdmin
- import_tasks: roles/web/tasks/main.yml
  when: not finished_web_tasks
- name: Configure PHPMyAdmin
  become: true
  # TODO maybe use https://docs.ansible.com/ansible/latest/dpkg_selections_module.html
  # TODO Is it necessary to run this before the installation of the phpmyadmin package?
  shell: |
    debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-user string {{db.username}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password {{db.password}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password {{db.phpmyadmin_password}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password {{db.phpmyadmin_password}}"
  notify: restart apache

- name: Add PHPMyAdmin configuration to Apache
  become: true
  lineinfile:
    path: /etc/phpmyadmin/apache.conf
    regexp: '(Alias /).*(/usr/share/phpmyadmin)'
    line: '\1{{ dir.phpmyadmin }} \2'
  notify: restart apache

- name: Finish development tasks
  lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_dev_tasks'
    line: 'finished_dev_tasks: True'

...
