---
# Certbot

# https://certbot.eff.org/docs/using.html#certbot-commands

- name: Add Certbot PPA
  become: yes
  apt_repository: state=present repo=ppa:certbot/certbot

- name: Install Certbot
  become: yes
  apt: name=python-certbot-apache state=present update_cache=yes

- name: Request certificate
  become: yes
  command: certbot --apache # certonly --webroot -w {{ dir.root }} -d {{ domain }}

# All generated keys and issued certificates can be found in /etc/letsencrypt/live/$domain

# TODO https://docs.ansible.com/ansible/latest/letsencrypt_module.html
#- letsencrypt:
#    account_key: /etc/pki/cert/private/account.key
#    csr: /etc/pki/cert/csr/sample.com.csr
#    dest: /etc/httpd/ssl/sample.com.crt
#    data: "{{ sample_com_challenge }}"

# TODO check for certificates
- name: Show certificates
  become: yes
  command: certbot certificates
  register: certificates
- debug:
    var: certificates.stdout_lines

- name: Add cron job for renewal
  cron: name=certbot special_time=monthly job="certbot renew" certbot renew --pre-hook "service apache2 stop" --post-hook "service apache2 start"

# certificate removal
# https://www.jeffgeerling.com/blog/2016/remove-single-certbot-letsencrypt-certificate-server
# certbot delete --cert-name example.com

- name: You need to solve the challenge to finish Certbot setup, see /etc/letsencrypt
  set_fact: state_https=false cacheable=true

...
