---

- name: Install PHP PEAR modules
  become: true
  pear: name={{item}} state=present
  with_items: { Auth_SASL, mail, mail_mime, Net_SMTP }

- name: Install Maildev for catching emails while developing
  become: true
  npm: name=maildev version=1.0.0-rc3 state=present global=yes
  notify:
  - maildev

- name: Setup Maildev to start on reboot
  become: true
  file: state=link src={{ dir.script }}/init_maildev.sh path=/etc/init.d/maildev mode='755'

- name: Create Maildev startup symlink
  # TODO insserv Script maildev is broken - incomplete LSB comment.
  become: true
  file: state=link src=/etc/init.d/maildev path=/etc/rc3.d/S99maildev
  notify:
  - maildev

- name: Finish Maildev installation
  set_fact: state_maildev=true cacheable=true

...
