---
# Setup hitchwiki
# based on install_funcs.sh by pgouveia.

#- name: Check status
#  include_tasks: status.yml

- name: Setup Monit
  include_tasks: monit.yml
  when: not state_monit

- name: Setup database server
  include_tasks: database.yml
  when: not state_db

- name: Setup webserver
  include_tasks: apache.yml
  when: not state_web

- set_fact: https=True
  when: mediawiki.protocol == 'https'

- name: Enable TLS
  include_tasks: tls.yml
  when: https and not state_https

- name: Setup Mediawiki
  include_tasks: mediawiki.yml
  #include_tasks: mw_import.yml
  when: not state_mw

# Development

- name: Setup development services
  include_tasks: development.yml
  when: env == 'dev'

# Production

- name: Setup production environment
  include_tasks: production.yml
  when: env == 'production'

# Finish!
- meta: flush_handlers

- name: Run post install scripts
  include_tasks: post_install.yml

- name: Status report
  include_tasks: status.yml

...
