---
# Setup hitchwiki
# based on install_funcs.sh by pgouveia.

- name: Setup database server
  include_tasks: database.yml
  when: not finished_db_tasks

- name: Setup webserver
  include_tasks: apache.yml
  when: not finished_web_tasks

- name: Setup mediawiki
  include_tasks: mediawiki.yml
  when: not finished_mw_tasks

- name: Setup TLS
  include_tasks: tls.yml
  when: mediawiki.protocol == 'https' and not finished_tls_tasks

- name: Setup development services
  include_tasks: dev.yml
  when: env == 'dev' and not finished_dev_tasks

- name: Setup production environment
  include_tasks: production.yml
  when: env == 'production'

- name: Status report
  include_tasks: status.yml

...
