---
# Setup hitchwiki
# based on install_funcs.sh by pgouveia.

- name: On first run following tests are likely to fail
  include_tasks: status.yml

- name: Prepare system
  include_tasks: system.yml
  when: not state_system

- name: Setup database server
  include_tasks: database.yml
  when: not state_db

- name: Setup webserver
  include_tasks: apache.yml
  when: not state_web

- name: Setup Mediawiki
  include_tasks: mediawiki.yml
  when: not state_mw

- set_fact: https=True
  when: mediawiki.protocol == 'https' or env == 'production'

- name: Test https://{{domain}}
  when: https
  uri: url=https://{{domain}} validate_certs=no
  register: tls_test

- name: Setup TLS
  include_tasks: tls.yml
  register: tls
  when: not 'OK' in tls_test.msg and https

- name: Setup environment
  include_tasks: "{{ env }}.yml"
  register: environment
  when: state_db and state_web and state_mw and not tls|failed

# Finish!
- meta: flush_handlers
  when: environment|succeeded

- name: Run tests again
  include_tasks: status.yml
  register: tests

- name: Run post install scripts
  include_tasks: scripts/roles/update/tasks/main.yml
  register: update
  when: environment|succeeded and tests|succeeded

- name: Finish
  include_tasks: _finished.yml
  when: update|succeded

...
