---
# Setup hitchwiki
# based on install_funcs.sh by pgouveia.

- name: Setup database server
  include_tasks: database.yml
  when: not state.db

- meta: flush_handlers

- name: Setup webserver
  include_tasks: apache.yml
  when: not state.web

- meta: flush_handlers

- name: Setup Mediawiki
  include_tasks: mediawiki.yml
  when: not state.mw

- name: Import Mediawiki content
  include_tasks: mw_import.yml
  when: not state.mw_import

- name: Setup TLS
  include_tasks: tls.yml
  when: mediawiki.protocol == 'https' and not state.tls

- name: Install Maildev
  include_tasks: maildev.yml
  when: env == 'dev' and not state.maildev

- name: Install PHPMyAdmin
  include_tasks: phpmyadmin.yml
  when: env == 'dev' and not state.phpmyadmin

- name: Setup production environment
  include_tasks: production.yml
  when: env == 'production' and not state.production

- meta: flush_handlers

- name: Status report
  include_tasks: status.yml

...
