---
# Monit
#  https://docs.ansible.com/ansible/latest/monit_module.html
#  https://mmonit.com/monit/documentation/monit.html

- name: Configure Monit
  become: yes
  template: src={{ dir.conf }}/monitrc dest=/etc/monitrc

- name: Check monit syntax
  become: yes
  command: monit -t
  register: monit_syntax
  ignore_errors: yes

- debug:
    msg: "{{ monit_syntax.stdout_lines }}"

- name: Reload monit
  become: yes
  command: monit reload
  register: monit_reloaded
  when: "'OK' in monit_syntax.stdout"

- name: Monit is set tup
  set_fact: state_monit=True cacheable=true
  when: monit_reloaded|succeeded

...
