---
# Monit
#  https://docs.ansible.com/ansible/latest/monit_module.html
#  https://mmonit.com/monit/documentation/monit.html

- name: Configure Monit
  become: yes
  template: src={{ dir.conf }}/monitrc dest=/etc/monit/monitrc mode=0700

- name: Check monit syntax
  become: yes
  command: monit -t
  register: monit_syntax

- name: Restart monit
  become: yes
  service: name=monit state=restarted

- name: Monit is set tup
  set_fact: state_monit=True cacheable=true

# fails in 2.4 https://github.com/ansible/ansible/issues/30614
#- name: Monitor sshd in monit
#  become: yes
#  monit: name=openssh-server state=monitored

...
