---
# Monit
#  https://docs.ansible.com/ansible/latest/monit_module.html
#  https://mmonit.com/monit/documentation/monit.html

- name: Configure Monit
  become: yes
  blockinfile:
    path: /etc/monitrc
    create: yes
    mode: 0700
    block: |
      set alert {{ admin_contact }}
      set alert {{ mediawiki.emergency_contact }} not on { instance, action }
      set httpd port 2812
          use address localhost  # only accept connection from localhost
          allow localhost        # allow localhost to connect to the server and  
          allow admin:monit      # require user 'admin' with password 'monit'
      include /etc/monit/conf-enabled/*
      include /etc/monit/monitrc.d/*

- name: Activate openssh-server in Monit
  become: yes
  file: state=link src=/etc/monit/conf-available/openssh-server path=/etc/monit/conf-enabled/openssh-server

- name: Check monit syntax
  become: yes
  command: monit -t
  register: monit_syntax
  ignore_errors: yes

- debug:
    msg: "{{ monit_syntax.stdout_lines }}"

- name: Reload monit
  become: yes
  command: monit reload
  register: monit_reloaded
  when: "'OK' in monit_syntax.stdout"

- name: Monitor openssh-server
  become: yes
  monit: name=openssh-server state=monitored
  when: monit_reloaded|succeeded
  ignore_errors: yes # TODO check why this fails with: process not presently configured with monit

- name: Monit is set tup
  set_fact: state_monit=True cacheable=true
  when: monit_reloaded|succeeded

...
