---
# Import MW content

- name: Configure Hitchwiki
  template: src={{ dir.conf }}/mediawiki.php dest={{ dir.wiki }}/LocalSettings.php

- name: Import interwiki table - https://www.mediawiki.org/wiki/Extension:Interwiki
  shell: mysql {{ db_credentials }} {{ mediawiki.db.database }} < "{{ dir.script }}/configs/interwiki.sql"
  register: interwiki

- name: Enable Semantic Mediawiki extension
  file: state=touch path={{ dir.wiki }}/extensions/SemanticMediaWikiEnabled
  # Mediawiki config file has a check for `SemanticMediaWikiEnabled` file:
  # basically SMW extensions are not included in MediaWiki before this
  # file exists, because it would cause errors when running
  # `maintenance/install.php`.

- name: Run the update script - https://www.mediawiki.org/wiki/Manual:Upgrading
  shell: "cd {{ dir.wiki }}; php maintenance/update.php --quick --conf {{ dir.mwconf }}"
  register: mw_update

- name: Pre-populate the AntiSpoof extension's table
  become: yes
  shell: chdir={{ dir.wiki }} php extensions/AntiSpoof/maintenance/batchAntiSpoof.php
  register: mw_antispoof

# SMW
- name: Setup Semantic Mediawiki
  # https://www.semantic-mediawiki.org/wiki/Help:Maintenance_script_%22setupStore.php%22
  command: chdir={{ dir.wiki }}/extensions/SemanticMediaWiki php ./maintenance/setupStore.php --quiet --conf {{ dir.mwconf }}
  register: setup_smw

- name: Create users
  become: yes
  command: chdir={{ dir.wiki }} php maintenance/createAndPromote.php {{ item.flags }} --force {{ item.name }} {{ phpmyadmin_password }}
  with_items:
    - { name: Hitchwiki, flags: --bureaucrat --sysop --bot }
    - { name: Hitchbot, flags: --bureaucrat --sysop --bot }
    - { name: Hitchhiker, flags:  }
  register: mw_users

- name: Set user's email
  command: mysql {{ db_credentials }} {{ mediawiki.db.database }} -e "UPDATE {{ mediawiki.db.prefix }}user SET user_email = '{{ item }}@{{ domain }}',  user_email_authenticated = '20141218000000' WHERE user_name = '{{ item }}'"
  with_items: { Hitchwiki, Hitchbot, Hitchhiker }
  register: user_mail

- name: Import Semantic templates and other MediaWiki special pages
  become: yes
  command: chdir=/var/www ./scripts/import_pages.sh
  register: import_pages
  ignore_errors: yes
- debug:
    var: import_pages.stdout_lines

- name: Run pending jobs and clear the queue
  command: chdir={{ dir.wiki }} php ./maintenance/runJobs.php
  register: mw_jobs

- name: Finish Mediawiki import
  set_fact: state_mw_import=true cacheable=true
  when: interwiki|succeeded and mw_update|succeeded and mw_antispoof|succeeded and setup_smw|succeeded and mw_users|succeeded and user_mail|succeeded and import_pages|succeeded and mw_jobs|succeeded

...
