---

# Parsoid depends on NodeSource (https://nodejs.org/en/download/package-manager)
#- tempfile: state=file suffix=nodejs
#  register: nodejs

#- name: Download NodeSoure 8.x installer
  #become: yes
  #uri: dest={{nodejs.path}} url=https://deb.nodesource.com/setup_8.x
  #shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  # TODO migrate the bash script here
  # TODO [WARNING]: Consider using get_url or uri module rather than running curl

- name: Add apt source for NodeSoure 8.x
  apt_repository: filename=nodesource.list state=present repo="deb https://deb.nodesource.com/node_8.x xenial main"

- name: Install nodejs
  become: yes
  apt: name=nodejs state=present update_cache=yes

- name: Link nodejs to node
  become: yes
  file: state=link src=/usr/bin/nodejs path=/usr/local/bin/node

# Parsoid is a NodeJS service used by VisualEditor (https://www.mediawiki.org/wiki/Parsoid/Setup)
- name: Add Parsoid apt key
  become: yes
  apt_key: id=90E9F83F22250DD7 keyserver=keys.gnupg.net

- name: Add Wikimedia repository
  become: yes
  apt_repository: state=present repo='deb https://releases.wikimedia.org/debian jessie-mediawiki main'

- name: Install Parsoid
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items: { apt-transport-https, parsoid }

- name: Create /etc/mediawiki/parsoid/
  become: yes
  file: path=/etc/mediawiki/parsoid/ owner={{ webserver_user }}

- name: Configure Parsoid
  become: yes
  copy: src=scripts/configs/parsoid_config.yaml dest=/etc/mediawiki/parsoid/config.yaml owner={{ webserver_user }} force=no

- name: Set domain in Parsoid
  become: yes
  lineinfile: path=/etc/mediawiki/parsoid/config.yaml regexp='hitchwiki.test' line={{ hw.domain }}

- name: Create Parsoid init script
  become: yes
  # TODO do we need to overwrite the packaged version?
  copy: force=no src={{ dir.script }}/configs/parsoid_initscript path=/etc/default/parsoid
  when: not lookup('file', '/etc/default/parsoid')

...
