---

# Parsoid depends on NodeSource (https://nodejs.org/en/download/package-manager)
- name: Add apt source for NodeSoure 8.x
  become: yes
  apt_repository: filename=nodesource.list state=present repo="deb https://deb.nodesource.com/node_8.x xenial main"

- name: Install nodejs
  become: yes
  apt: name=nodejs state=present update_cache=yes

- name: Link nodejs to node
  become: yes
  file: state=link src=/usr/bin/nodejs path=/usr/local/bin/node

# Parsoid is a NodeJS service used by VisualEditor (https://www.mediawiki.org/wiki/Parsoid/Setup)
- name: Add Parsoid apt key
  become: yes
  apt_key: id=90E9F83F22250DD7 keyserver=keys.gnupg.net

- name: Add Wikimedia repository
  become: yes
  apt_repository: state=present repo='deb https://releases.wikimedia.org/debian jessie-mediawiki main'

- name: Install Parsoid
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items: { apt-transport-https, parsoid }

- name: Create /etc/mediawiki/parsoid/
  become: yes
  file: path=/etc/mediawiki/parsoid/ owner={{ apache.user }}

- name: Configure Parsoid
  become: yes
  copy: src=scripts/configs/parsoid_config.yaml dest=/etc/mediawiki/parsoid/config.yaml owner={{ apache.user }} force=no

- name: Set domain in Parsoid
  become: yes
  lineinfile: path=/etc/mediawiki/parsoid/config.yaml regexp='hitchwiki.test' line={{ mediawiki.domain }}

# TODO do we need to overwrite the packaged version?
#- name: Create Parsoid init script
#  become: yes
#  shell: cp {{ dir.script }}/configs/parsoid_initscript /etc/default/parsoid

- name: Finish parsoid setup
  lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  parsoid:'
    line: "  parsoid: True"
  notify:
  - load

...
