---
# Parsoid is a NodeJS service used by VisualEditor (https://www.mediawiki.org/wiki/Parsoid/Setup)
- name: Add Parsoid apt key
  become: yes
  apt_key: id=90E9F83F22250DD7 keyserver=keys.gnupg.net

- name: Add Wikimedia repository
  become: yes
  apt_repository: state=present repo='deb https://releases.wikimedia.org/debian jessie-mediawiki main'

- name: Install Parsoid
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items: { apt-transport-https, parsoid }

- name: Create /etc/mediawiki/parsoid/
  become: yes
  file: state=directory path=/etc/mediawiki/parsoid/ owner={{ apache.user }}

- name: Configure Parsoid
  become: yes
  template: src=scripts/configs/parsoid_config.yaml dest=/etc/mediawiki/parsoid/config.yaml owner={{ apache.user }} force=no

# TODO do we need to overwrite the packaged version?
#- name: Create Parsoid init script
#  become: yes
#  shell: cp {{ dir.script }}/configs/parsoid_initscript /etc/default/parsoid

- name: Finish parsoid installation
  set_fact: state_parsoid=true cacheable=true

...
