---
# Productive environment

- name: Setup Monit
  include_tasks: monit.yml

- name: Finish installation
  lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  production:'
    line: '  production: True'
  notify:
  - load

...
