---
# Status report

- lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  finished:'
    line: '  finished: True'
  register: finished
  when: state.system and state.db and state.web and state.mw and state.mw_import and state.parsoid and ((state.production and state.tls) or (state.phpmyadmin and state.maildev))
  notify:
  - load
- lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  finished:'
    line: '  finished: False'
  when: finished|skipped
  notify:
  - load

# Summary
- include_tasks: _failed.yml
  when: not state.finished

- include_tasks: _finished.yml
  when: state.finished

...
