---
# Status report

- name: Is facts.d present?
  shell: "[ -d /etc/ansible/facts.d ]"
  register: spyc
  ignore_errors: yes

- name: Is monit started?
  become: yes
  shell: monit status
  register: monit
  ignore_errors: yes

- name: Is the webserver reachable?
  uri: url=http://localhost
  register: apache
  ignore_errors: yes

- name: Is mysql started?
  shell: "[ -e /var/run/mysqld/mysqld.sock ]"
  register: mysql
  ignore_errors: yes

- name: Is parsoid started?
  uri: url=http://localhost:8142
  register: parsoid
  ignore_errors: yes

- name: Is TLS enabled?
  shell: "[ -f /etc/apache2/sites-enabled/default-ssl.conf ]"
  register: tls
  ignore_errors: yes

- set_fact: state_web=True
  when: apache.status == 200
- set_fact: state_db=True
  when: mysql|succeeded
- set_fact: state_mw=True state_parsoid=True
  when: parsoid.status == 200
- set_fact: state_production=True
  when: monit|succeeded
- set_fact: state_system=True
  when: spyc|succeeded
- set_fact: state_https=True
  when: tls|succeeded

...
