---
# Setup TLS

# apache mod md
- include_tasks: tls_selfsigned.yml
  when: mediawiki.protocol == 'https' and env == 'env'

# Let's Encrypt - apache mod md
- include_tasks: tls_md.yml
  when: mediawiki.protocol == 'https' and env == 'production'

# Let's Encrypt - certbot
#- include_tasks: tls_certbot.yml
#  when: env == 'production'

...
