---
# Setup TLS

- include_tasks: tls_selfsigned.yml

# TODO untested: Let's Encrypt - apache mod md
# "unless it's at least beta-level, we should use just letsencrypt's certbot+cron"
#- include_tasks: tls_md.yml
#  when: mediawiki.protocol == 'https' and env == 'production'

# Let's Encrypt - certbot
- include_tasks: letsencrypt.yml
  when: env == 'production'

- name: Is https setup?
  debug:
    var: state_https

...
