---
# Transport Layer Security
- name: Create the SSL Certificate
  become: yes
  shell: >
    openssl req -subj "/CN={{ mediawiki.domain }}/O={{ mediawiki.sitename }}/C=DE" -x509 -nodes
    -days 365 -newkey rsa:2048
    -keyout /etc/ssl/private/apache-selfsigned.key
    -out /etc/ssl/certs/apache-selfsigned.crt

- name: Generate a Diffie-Hellman group
  become: yes
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

- name: Create SSL configuration for Apache
  # TODO
  shell: |
    echo "File: /etc/apache2/conf-available/ssl-params.conf"
    # Using temporary file `{{ dir.root }}/tmp/ssl-params.conf` because
    #  output redirection (`>>`) is done by the shell, not by `cat`,
    #  and thus `sudo` won't work.
    # http://askubuntu.com/a/230482
    cd {{ dir.root }}
    [[ -d tmp ]] || mkdir tmp
    cd tmp
    sudo cat <<EOT >> ssl-params.conf
    # from https://cipherli.st/
    # and https://raymii.org/s/tutorials/Strong_SSL_Security_On_Apache2.html
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    SSLProtocol All -SSLv2 -SSLv3
    SSLHonorCipherOrder On
    # Disable preloading HSTS for now.  You can use the commented out header line that includes
    # the "preload" directive if you understand the implications.
    #Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
    Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains"
    Header always set X-Frame-Options DENY
    Header always set X-Content-Type-Options nosniff
    # Requires Apache >= 2.4
    SSLCompression off
    SSLSessionTickets Off
    SSLUseStapling on
    SSLStaplingCache "shmcb:logs/stapling-cache(150000)"
    SSLProtocol ALL -SSLv2 -SSLv3
    SSLHonorCipherOrder On
    SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ## For Newer Apache+OpenSSL:
    ## If you have Apache 2.4.8 or later and OpenSSL 1.0.2 or later, you can
    ## generate and specify your DH params file:
    ## https://raymii.org/s/tutorials/Strong_SSL_Security_On_Apache2.html#Forward_Secrecy_&_Diffie_Hellman_Ephemeral_Parameters
    ## https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslopensslconfcmd
    #SSLOpenSSLConfCmd DHParameters "/etc/ssl/certs/dhparam.pem"
    ## OR for older Apache+OpenSSL:
    ## From http://serverfault.com/a/693244
    ## On Debian Wheezy upgrade apache2 to 2.2.22-13+deb7u4 or later and openssl
    ## to 1.0.1e-2+deb7u17. The above SSLCipherSuite does not work perfectly,
    ## instead use the following as per this blog:
    ## https://blog.cscholz.io/debian-wheezy-apache-logjam/10492/
    SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA:!DHE-RSA-AES256-SHA256:!DHE-RSA-CAMELLIA128-SHA:!DHE-RSA-CAMELLIA256-SHA
    EOT
    sudo mv "{{ dir.root }}/tmp/ssl-params.conf" /etc/apache2/conf-available/ssl-params.conf
    cd {{ dir.root }}
    sudo rm -fr "{{ dir.root }}/tmp/"

- name: Modify default SSL VirtualHost configuration file for Apache
  shell: |
    echo "File: /etc/apache2/sites-available/default-ssl.conf"
    # Using temporary file `{{ dir.root }}/tmp/default-ssl.conf` because
    #  output redirection (`>>`) is done by the shell, not by `cat`,
    #  and thus `sudo` won't work.
    # http://askubuntu.com/a/230482
    cd {{ dir.root }}
    [[ -d tmp ]] || mkdir tmp
    cd tmp
    sudo cat <<EOT > default-ssl.conf
    <IfModule mod_ssl.c>
            <VirtualHost _default_:443>
                    ServerAdmin webmaster@{{ mediawiki.domain }}
                    ServerName {{ mediawiki.domain }}
                    DocumentRoot {{ dir.root }}/public
                    ErrorLog \${APACHE_LOG_DIR}/error.log
                    CustomLog \${APACHE_LOG_DIR}/access.log combined
                    SSLEngine on
                    SSLCertificateFile      /etc/ssl/certs/apache-selfsigned.crt
                    SSLCertificateKeyFile   /etc/ssl/private/apache-selfsigned.key
                    <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                    SSLOptions +StdEnvVars
                    </FilesMatch>
                    <Directory /usr/lib/cgi-bin>
                                    SSLOptions +StdEnvVars
                    </Directory>
                    BrowserMatch "MSIE [2-6]" \
                                    nokeepalive ssl-unclean-shutdown \
                                    downgrade-1.0 force-response-1.0
                    # MSIE 7 and newer should be able to use keepalive
                    BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
            </VirtualHost>
    </IfModule>
    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
    EOT
    sudo mv {{ dir.root }}/tmp/default-ssl.conf" /etc/apache2/sites-available/default-ssl.conf
    cd {{ dir.root }}
    sudo rm -fr {{ dir.root }}/tmp/

- name: Enable ssl and headers modules for Apache
  become: yes
  apache2_module: name={{item}} state=present
  with_items: { ssl, headers }
  notify: 
  - apache

- name: Enable SSL Virtual Host
  become: yes
  command: a2ensite default-ssl

- name: Enable ssl-params.conf file
  become: yes
  command: a2enconf ssl-params

- name: Apache config test
  become: yes
  command: apache2ctl configtest
  register: syntaxcheck

- name: Successfully setup TLS
  lineinfile:
    path: "{{ dir.state }}"
    regexp: '^  tls:'
    line: "  tls: True"
  notify:
  - load
  - apache
  when: syntaxcheck|succeeded

...
