---
# Transport Layer Security

# TODO https://www.jeffgeerling.com/blog/2017/self-signed-certificates-ansible-local-testing-nginx
- name: Create self-signed certificate
  become: yes
  command: >
    openssl req -x509 -nodes -subj '/CN={{ domain }}' -days 365
    -newkey rsa:4096 -sha256 -keyout {{ item.key }} -out {{ item.cert }}
  with_items: "{{ self_signed_certs }}"

- name: Generate a Diffie-Hellman group
  become: yes
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  register: dhg

- name: Create SSL configuration for Apache
  become: yes
  template: src=configs/ssl-params.conf dest=/etc/apache2/conf-available/ssl-params.conf

- name: Modify default SSL VirtualHost configuration file for Apache
  become: yes
  template: src=configs/default-ssl.conf dest=/etc/apache2/sites-available/default-ssl.conf

- name: Redirect non-https requests
  lineinfile:
    - path: /etc/apache2/sites-enabled/hitchwiki.conf 
    - insertafter: '^  DocumentRoot'
    - regexp: '^  Redirect "http:/{{ domain }}/$"'
    - -line: '  Redirect "http:/{{ domain }}/$" "https://{{ domain }}"'

- name: Enable ssl and headers modules for Apache
  become: yes
  apache2_module: name={{item}} state=present
  with_items: { ssl, headers }

- name: Enable SSL Virtual Host
  become: yes
  command: a2ensite default-ssl

- name: Enable ssl-params.conf file
  become: yes
  command: a2enconf ssl-params

- name: Apache config test
  become: yes
  command: apache2ctl configtest
  register: syntaxcheck

- name: Successfully setup self-signed certificate
  set_fact: state_https=false cacheable=true
  notify:
  - apache
  when: syntaxcheck|succeeded
- meta: flush_handlers

...
