---
# Show versions

- name: Fetching apache version
  shell: apachectl -V
  register: apache
- debug:
    var: apache.stdout_lines
  when: apache|succeeded

- name: Fetching php version
  shell: php -v
  register: php
- debug:
    var: php.stdout_lines
  when: php|succeeded

- name: Fetching npm version
  shell: npm --version
  register: npm
- debug:
    var: npm.stdout_lines
  when: npm|succeeded

- name: Fetching node version
  shell: nodejs --version
  register: nodejs
- debug:
    var: nodejs.stdout_lines
  when: nodejs|succeeded

- name: Fetching bower version
  shell: bower --version
  register: bower
- debug:
    var: bower.stdout_lines
  when: bower|succeeded

- name: Fetching openssl version
  shell: openssl version
  register: openssl
- debug:
    var: openssl.stdout_lines
  when: openssl|succeeded

- name: Fetching composer version
  shell: composer --version
  register: composer
- debug:
    var: composer.stdout_lines
  when: composer|succeeded

...
