---
# Hitchwiki update: update MediaWiki, its database, extensions and assets
- name: Run pending jobs and clear the queue
  command: chdir={{ dir.wiki }} php ./maintenance/runJobs.php

- name: Regenerate LocalSettings.php
  template: src={{ dir.conf }}/mediawiki.php dest={{ dir.wiki }}/LocalSettings.php

- name: Update Hitchwiki dependencies using composer.local.json
  command: chdir={{ dir.wiki }} composer update --no-progress --no-interaction

- name: Update VisualEditor
  shell: cd "{{ dir.wiki }}/extensions/VisualEditor" git pull; git submodule update --init

- name: Run update script for Semantic MediaWiki
  command: chdir={{ dir.wiki }} php extensions/SemanticMediaWiki/maintenance/SMW_refreshData.php -d 50 -v

- name: Import forms, templates, etc.
  command: chdir={{ dir.root }}/.. "{{ dir.script }}/import_pages.sh"

...
