---
# Common ansible handlers

   - name: print versions
     apache2 --version
     php -v
     npm --version
     node --version
     bower --version
     openssl version
     composer --version

   - name: status
     Hitchwiki is now installed!
     Apache is up. Open http://$HW__geieral__domain/ in your browser.
     Parsoid is running. Open http://$HW__general__domain:8142 in your browser.
     Maildev is running, inspect emails in your browser http://$HW__general__domain:1080
     PHPMyAdmin is running, access database via http://$HW__general__domain/phpmyadmin
     Suspend the virtual machine by calling 'vagrant suspend'.
     When you're ready to begin working again, just run 'vagrant up'.
     To re-install, run 'vagrant destroy && vagrant up'.
     Read more from http://github.com/Hitchwiki/hitchwiki
     Good luck!

---
