---
# Setup hitchwiki
# based on install_funcs.sh by pgouveia.

- name: Check status
  include_tasks: roles/status/tasks/main.yml

- name: Prepare system
  include_tasks: system.yml
  when: not configured.system
  notify: "update system"

- name: Setup database server
  include_tasks: database.yml
  when: not configured.db

- name: Setup webserver
  include_tasks: apache.yml
  when: not configured.web

- name: Setup Mediawiki
  include_tasks: mediawiki.yml
  when: not configured.mw

- set_fact: https=True
  when: mediawiki.protocol == 'https' or env == 'production'

- name: Setup TLS
  include_tasks: tls.yml
  when: not configured.tls and https

- name: Setup dev environment
  include_tasks: dev.yml
  when: env == 'dev' && not configured.dev

- name: Setup production environment
  include_tasks: production.yml
  when: env == 'production' && not configured.production && not started.monit

- meta: flush_handlers

- name: Print status
  include_tasks: roles/status/tasks/main.yml


...
