---
# Setup hitchwiki
# based on install_funcs.sh by pmgouveia.

- shell: "[ -d /etc/ansible/facts.d ]"
  ignore_errors: yes
  notify: status

- name: Fetch remote settings
  fetch: src=/var/www/configs/settings.yml dest=status/{{ ansible_host }}/ flat=yes fail_on_missing=no validate_checksum=yes

- name: Load settings
  include_vars: "{{ item }}"
  with_first_found:
    - "status/{{ ansible_host }}/settings.yml"
    - configs/settings.yml
    - configs/settings-example.yml
    - /var/www/configs/settings.yml
    - /var/www/configs/settings-example.yml

- name: Check if settings.yml is up to date
  failed_when: dir is undefined
  debug:
    var: dir
- meta: flush_handlers

- name: Prepare system
  import_tasks: system.yml
  when: not configured.system
  notify: "update system"

- name: Setup database server
  import_tasks: database.yml
  when: not configured.db or not started.mysql

- name: Setup webserver
  import_tasks: apache.yml
  when: not configured.web or not started.apache

- name: Setup Mediawiki
  import_tasks: mediawiki.yml
  when: not configured.mw or not started.parsoid

- name: Setup dev environment
  include_tasks: dev.yml
  when: env == 'dev' and not configured.dev

- name: Setup production environment
  include_tasks: production.yml
  when: env == 'production' and not configured.production

- name: Is TLS requested?
  debug: msg="{{ env }} / {{ mediawiki.protocol }}"
- name: Activate TLS
  set_fact: https=True
  when: "'https' in mediawiki.protocol or 'production' in env"
- name: Setup TLS
  include_tasks: tls.yml
  when: https and not configured.tls

- name: Setup Monit
  import_tasks: monit.yml
  when: not configured.monit

- meta: flush_handlers

- name: Update mediawiki
  include_role: name=update

- name: Print status
  import_tasks: roles/status/tasks/main.yml

...
