---
# Setup hitchwiki
# based on install_funcs.sh by pgouveia.

- name: Has configs/settings-example.yml been copied to configs/settings.yml?
  include_vars: ./configs/settings.yml
  when: lookup('file', 'configs/settings.yml')

- name: This should show path settings or settings.yml is not up to date
  debug:
    var: dir
  failed_when: dir is undefined

- name: Check status
  include_tasks: roles/status/tasks/main.yml

- name: Prepare system
  include_tasks: system.yml
  when: not configured.system
  notify: "update system"

- name: Setup database server
  include_tasks: database.yml
  when: not configured.db

- name: Setup webserver
  include_tasks: apache.yml
  when: not configured.web

- name: Setup Mediawiki
  include_tasks: mediawiki.yml
  when: not configured.mw

- set_fact: https=True
  when: 'https' in mediawiki.protocol or 'production' in env

- debug: msg="{{ mediawiki.protocol }} {{ env }}"

- name: Setup TLS
  include_tasks: tls.yml
  when: https and not configured.tls

- name: Setup dev environment
  include_tasks: dev.yml
  when: env == 'dev' and not configured.dev

- name: Setup production environment
  include_tasks: production.yml
  when: env == 'production' and not configured.production and not started.monit

- meta: flush_handlers

- name: Print status
  include_tasks: roles/status/tasks/main.yml


...
