---
# Setup hitchwiki
# based on install_funcs.sh by pmgouveia.

- debug: var=ansible_user
- debug: var=ansible_distribution
- debug: var=ansible_distribution_release
- set_fact:
    os_version: "{{ ansible_distribution_release }}"
  notify: status
- set_fact:
    os_version: stretch
  when: os_version == 'NA'
- set_fact: keyserver=hkp://keyserver.ubuntu.com:80
  when: keyserver is not defined

# When managing multiple VPS we want to store their settings locally
- name: Fetch remote settings # TODO check if that overwrites a locally changed copy
  fetch: src={{dir.settings}} dest=logs/status/{{ ansible_host }}/ flat=yes fail_on_missing=no validate_checksum=no

# if it was not there, we copy our local settings or use the example version
- name: Copy settings.yml
  copy: src={{item}} dest={{dir.settings}} owner={{user}} group={{apache.group}}
  with_first_found:
    - "logs/status/{{ ansible_host }}/settings.yml" # transfer the one fetched before
    - /root/settings.yml # when running deploy_remote.sh with preset config
    - /var/www/configs/settings.yml
    - /var/www/configs/settings-example.yml
  notify: status

- name: Reload settings
  include_vars: "{{dir.settings}}"

- name: Check if relevant variables are defined
  debug: var={{item}}
  register: var
  failed_when: var is undefined
  with_items: { dir, domain, env, admin_contact, mediawiki.protocol, apache.user }

- name: Check for spyc
  stat: path=/var/www/public/mustangostang
  register: spyc
- meta: flush_handlers

# import versus include https://serverfault.com/questions/875247/whats-the-difference-between-include-tasks-and-import-tasks
# - use import when you deal with logical "units" , for example to separate long list of tasks into subtask files
# - use include to deal with different workflows and take decisions based on some dynamically gathered facts
# At compile time 'configured' is undefined, so we need to use include_tasks with the downside that handlers can't be called
# Tradeoffs and Pitfalls Between Includes and Imports https://docs.ansible.com/ansible/devel/playbooks_reuse.html
#  "You cannot use notify to trigger a handler name which comes from inside a dynamic include (see note below)."

- name: Prepare system
  include_tasks: system.yml
  when: not configured.system
  notify: "update system"

- name: Setup database server
  include_tasks: database.yml
  when: not configured.db or not started.mysql
  notify: "restart db"

- name: Setup webserver
  include_tasks: apache.yml
  when: not configured.web or not started.apache
  notify: restart apache

- name: Setup Mediawiki
  include_tasks: mediawiki.yml
  when: not configured.mw or not started.parsoid

- name: Setup dev environment
  include_tasks: dev.yml
  when: env == 'dev' and not configured.dev
  notify:
    - restart apache
    - start maildev

- name: Setup production environment
  include_tasks: production.yml
  when: env == 'production' and not configured.production
  notify: restart db

- name: Disable MW debugging
  blockinfile:
    path: "{{dir.wiki}}/LocalSettings.php"
    state: absent
    block: |
      $wgShowExceptionDetails = true;
      $wgShowDBErrorBacktrace = true;

- name: Setup Monit
  include_tasks: monit.yml
  when: not configured.monit

- debug: msg="{{ env }} / {{ mediawiki.protocol }}"
- name: Enable TLS
  include_tasks: tls.yml
  when: mediawiki.protocol == 'https' or env == 'production'
  notify:
    - restart apache
- meta: flush_handlers

- name: Print status
  include_tasks: roles/status/tasks/main.yml

- name: Make sure necessary services are up
  meta: end_play
  when: not started.mysql or not started.apache or not started.parsoid or not started.monit

...
