---
# Setup mediawiki with Parsoid and fill it with content

# Prepare database
- name: Drop Mediawiki database
  mysql_db: name={{ mediawiki.db.database }} state=absent login_user={{ mediawiki.db.username }} login_password={{ mediawiki.db.password }}
  when: mediawiki.db.clean_on_setup is defined and mediawiki.db.clean_on_setup

- name: Create database
  mysql_db: name={{ mediawiki.db.database }} state=present encoding=utf8 collation=utf8_general_ci login_user={{ mediawiki.db.username }} login_password={{ mediawiki.db.password }}

# Mediawiki installation
- name: Clean wiki folder
  become: yes
  file: state=absent path={{ item }}
  with_items: "{ {{ dir.wiki }}, composer.lock }"
  when: mediawiki.clean_on_setup is defined and mediawiki.clean_on_setup

- name: Install mediawiki
  composer: command=install no_dev=True working_dir=/var/www/

- name: Create wiki directories
  become: yes
  file: state=directory path={{ item }} owner=1050 group={{ apache.group }} mode=774
  with_items:
    - "{{ dir.root }}/tmp/sessions"
    - "{{ dir.wiki }}/cache"
    - "{{ dir.wiki }}/images/cache"
    - "{{ dir.wiki }}/dumps"
    - "{{ dir.wiki }}/extensions"

- name: Configure composer
  template: src=configs/composer.local.json dest={{ dir.wiki }}/composer.local.json

- name: Download basic MediaWiki extensions
  composer: command=update no_dev=True working_dir={{ dir.wiki }}
  register: composer_update

- name: Setup Mediawiki extensions
  composer: working_dir={{dir.wiki}} command=run-script no_dev=True arguments="post-install-cmd -d ./extensions/{{ item }}"
  with_items: [ HWMap, HitchwikiVector, HWRatings, HWLocationInput ]

#- name: Stop Maps extension from setting up a {{#coordinates}} parser function hook
  # that conflicts with GeoData extensions's {{#coordinates}} parser function hook
  #
  # We are using GeoData's function in templates to index articles with spatial info
  #
  # TODO: any solution that is cleaner than this temporary dirty hack..
  #echo "Stop Maps extension from setting up a {{#coordinates}} parser function hook..."
  # sed -i -e '111i\ \ /*' -e '116i\ \ */' "$WIKIDIR/extensions/Maps/Maps.php" # wrap damaging lines of code as a /* comment */
  # sed -i -e '112i\ \ // This code block has been commented out by Hitchwiki install script.
  # See scripts/server_install.sh for details\n' "$WIKIDIR/extensions/Maps/Maps.php"

- name: Run Mediawiki install script - https://www.mediawiki.org/wiki/Manual:Installing_MediaWiki
  # sets up wiki in one language ("en") and creates admin user "hitchwiki" with password {{ phpmyadmin_password }}
  # Usage: php install.php [--conf|--confpath|--dbname|--dbpass|--dbpassfile|--dbpath|--dbport|--dbprefix|--dbschema|--dbserver|--dbtype|--dbuser|--env-checks|--globals|--help|--installdbpass|--installdbuser|--lang|--memory-limit|--pass|--passfile|--profiler|--quiet|--scriptpath|--server|--wiki] [name] <admin>
  command: chdir={{ dir.wiki }} php maintenance/install.php \
    --dbuser {{ mediawiki.db.username }} --dbpass {{ mediawiki.db.password }} \
    --dbname {{ mediawiki.db.database }} --dbprefix {{ mediawiki.db.prefix }} \
    --dbtype mysql --pass {{ phpmyadmin_password }} \
    --scriptpath /{{ dir.wiki }} --lang en "{{ mediawiki.sitename }}" hitchwiki
  register: mw_install
  ignore_errors: yes # this fails on reruns if mediawiki.clean_on_setup is not true

# MW visual editor
- name: Install MW visual editor
  git:
    clone: yes
    repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/VisualEditor.git
    version: "{{ mediawiki.branch }}"
    dest: "{{ dir.wiki }}/extensions/VisualEditor"
    depth: 1
    track_submodules: yes
    force: yes
  # Since it requires submodules, we don't install this using composer
  # https://www.mediawiki.org/wiki/Extension:VisualEditor

- name: Grant wiki folder to webuser group
  become: yes
  at: command="chgrp {{ apache.group }} -R {{ dir.wiki }}" count=1 units=minutes
  #file: path={{ dir.wiki }} recurse=yes group={{ apache.group }}

- name: Grant wiki settings to webuser
  become: yes
  file: path={{ dir.conf }}/{{item}} group={{ apache.group }}
  with_items: { mediawiki-lang.php, languages.ini, mediawiki-extensions.php }

- name: Import Mediawiki content # MW db actions
  include_tasks: mw_import.yml

- name: Install Parsoid
  include_tasks: parsoid.yml
  when: not configured.parsoid

- name: Add cron job for daily localisation updates
  cron: name=LocalisationUpdate special_time=daily  job="php {{ dir.wiki }}/extensions/LocalisationUpdate/update.php --quiet"
  # See https://github.com/Hitchwiki/hitchwiki/issues/109

...
