---
# Productive environment
- name: Disable maildev
  become: yes
  file: path=/etc/init.d/maildev state=absent
  when: configured.maildev
  notify:
    - stop maildev
  ignore_errors: yes

- name: Remove PHPMyAdmin
  become: yes
  apt: name=phpmyadmin state=absent

- name: Secure DB server
  # https://mariadb.com/kb/en/library/mysql_secure_installation
  # https://github.com/twitter/mysql/blob/master/scripts/mysql_secure_installation.sh#L170
  # Make sure that NOBODY can access the server without a password
  shell: |
    mysql {{ db_credentials }} -e "UPDATE mysql.user SET Password = '{{ mediawiki.db.password }}'  WHERE User = 'root'"
    mysql {{ db_credentials }} -e "DROP USER ''@'localhost'"
    mysql {{ db_credentials }} -e "DROP USER ''@'$(hostname)'"
    mysql {{ db_credentials }} -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
    mysql {{ db_credentials }} -e "FLUSH PRIVILEGES"
  register: secure_db
  when: 0 # TODO check why this makes the server inaccessible
  ignore_errors: yes
- debug:
    var: secure_db.stderr_lines

- name: Setup discourse
  include_tasks: discourse.yml
  when: discourse is defined and discourse.enabled and not configured.discourse

...
