---

# As root
- name: Change hostname
  become: yes
  hostname: name={{ hostname }}

- name: Add {{ hostname }} to `/etc/hosts`
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: 127.0.0.1 localhost {{ hostname }}

- name: adduser {{ user }}
  become: yes
  user: generate_ssh_key=yes name={{ user }} uid=1050 shell=/bin/bash
  # https://docs.ansible.com/ansible/latest/user_module.html

- name: Set .ssh/authorized_keys from file
  authorized_key: user={{ user }}  state=present key="{{ lookup('file', 'configs/authorized_keys') }}"

- name: Add {{ user }}'s ssh key for local login
  remote_user: "{{ user }}"
  # TODO
  #lineinfile: line=
  shell: cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

- name: Install pip
  become: yes
  apt: name={{ item }} state=present
  with_items: { git, python-pip }

- name: Install ansible and upgrade pip
  pip: name={{ item }} state=latest
  with_items: { pip, ansible }

- name: Clone hitchwiki repository
  remote_user: "{{ user }}"
  git:
    dest: ~/src
    repo: https://github.com/traumschule/hitchwiki # TODO change later
    version: ansible
    depth: 1
# set

# TODO remove later
- name: Track ansible branch
  shell: cd ~/hitchwiki; git branch --set-upstream-to=origin/ansible ansible

- name: Link /home/{{ user }}/src to /var/www
  become: yes
  file: state=link force=yes src="/home/{{ user }}/hitchwiki" path=/var/www

- debug:
    msg: Success! Now run ansible-playbook hitchwiki.yml`.

...
