---
# Setup mediawiki with Parsoid and fill it with content.

- name: Point Mediawiki configuration to Hitchwiki configuration file
  # Config file is stored elsewhere, require it from MW's LocalSettings.php
  file: state=link src={{SCRIPTDIR}}/configs/mediawiki_LocalSettings.php path={{WIKIDIR}}/LocalSettings.php force=yes

- name: Install mediawiki
  composer: command=install no_dev=True working_dir={{ROOTDIR}}

- name: Create wiki directories
  shell: |
    mkdir -p {{ROOTDIR}}/tmp/sessions
    mkdir {{WIKIDIR}}/cache
    mkdir -p {{WIKIDIR}}/images/cache
    mkdir {{WIKIDIR}}/dumps

- name: Set wiki folder permissions ({{ROOTDIR}})
  become: yes
  acl: entity={{hw_owners}} path={{ROOTDIR}} recursive=yes state=present #permissions=g+rw

- name: Set wiki folder permissions ({{ROOTDIR}}/tmp/sessions)
  become: yes
  acl: entity={{hw_owners}} path={{ROOTDIR}}/tmp/sessions recursive=yes state=present permissions=ug+rw

- name: Set wiki folder permissions ({{WIKIDIR}}/images)
  become: yes
  acl: entity={{hw_owners}} path={{WIKIDIR}}/images recursive=yes state=present permissions=ug+rw

- name: Set wiki folder permissions ({{WIKIDIR}}/cache)
  become: yes
  acl: entity={{hw_owners}} path={{WIKIDIR}}/cache recursive=yes state=present permissions=ug+rw

- name: Configure composer
  become: yes
  copy: src={{CONFDIR}}/composer.local.json dest={{WIKIDIR}}/composer.local.json

- name: Download basic MediaWiki extensions
  composer: command=update no_dev=True working_dir={{WIKIDIR}}

- name: Run Mediawiki install script
  # https://www.mediawiki.org/wiki/Manual:Installing_MediaWiki#Run_the_installation_script
  # Usage: php install.php [--conf|--confpath|--dbname|--dbpass|--dbpassfile|--dbpath|--dbport|--dbprefix|--dbschema|--dbserver|--dbtype|--dbuser|--env-checks|--globals|--help|--installdbpass|--installdbuser|--lang|--memory-limit|--pass|--passfile|--profiler|--quiet|--scriptpath|--server|--wiki] [name] <admin>
  # sets up wiki in one language ("en")
  # creates one admin user "hitchwiki" with password "autobahn"
  command: chdir={{ WIKIDIR }} |
    php maintenance/install.php --conf "{{ MWCONFFILE }}" \   
    --dbuser {{ HW__db__username }} \
    --dbpass {{ HW__db__password }} \
    --dbname {{ HW__db__database }} \
    --dbtype mysql \
    --pass autobahn \
    --scriptpath /{{ WIKIFOLDER }} \
    --lang en "{{ HW__general__sitename }}" hitchwiki

- name: install MW visual editor
  # Since it requires submodules, we don't install this using composer
  # https://www.mediawiki.org/wiki/Extension:VisualEditor
  git:
    clone: yes
    repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/VisualEditor.git
    version: "{{ HW__general__mw_branch }}"
    dest: "{{ WIKIDIR }}/extensions/VisualEditor"
    depth: 1
    track_submodules: yes
  # TODO exists
  ignore_errors: yes

- name: Setup Mediawiki extensions
  composer: action=run-script working_dir={{WIKIDIR}} arguments="post-install-cmd -d ./extensions/{{ tem}}"
  with_items: { HWMap, HitchwikiVector, HWRatings, HWLocationInput }

#- name: Stop Maps extension from setting up a {{#coordinates}} parser function hook
  # that conflicts with GeoData extensions's {{#coordinates}} parser function hook
  #
  # We are using GeoData's function in templates to index articles with spatial info
  #
  # TODO: any solution that is cleaner than this temporary dirty hack..
  #echo "Stop Maps extension from setting up a {{#coordinates}} parser function hook..."
  # sed -i -e '111i\ \ /*' -e '116i\ \ */' "$WIKIDIR/extensions/Maps/Maps.php" # wrap damaging lines of code as a /* comment */
  # sed -i -e '112i\ \ // This code block has been commented out by Hitchwiki install script.
  # See scripts/server_install.sh for details\n' "$WIKIDIR/extensions/Maps/Maps.php"

- name: Empty database
  mysql_db: name={{db.database}} state=absent
  
- name: Create database
  mysql_db: name={{db.database}} state=present encoding=utf8 collation=utf8_general_ci
  #IFS=$'\n' languages=($(echo "SHOW DATABASES;" | mysql -u$username -p$password | grep -E '^hitchwiki_..$' | sed 's/^hitchwiki_//g'))

- name: Import interwiki table
  # https://www.mediawiki.org/wiki/Extension:Interwiki
  mysql_db: name={{db.database}} state=import target="{{SCRIPTDIR}}/configs/interwiki.sql"

- name: Setup database for several MW extensions (SemanticMediaWiki, AntiSpoof etc)
  # Mediawiki config file has a check for `SemanticMediaWikiEnabled` file:
  # basically SMW extensions are not included in MediaWiki before this
  # file exists, because it would cause errors when running
  # `maintenance/install.php`.
  # TODO use file
  shell: |
    touch {{ WIKIDIR }}/extensions/SemanticMediaWikiEnabled
    cd  {{ WIKIDIR }}
    php maintenance/update.php --quick --conf "$MWCONFFILE"

- name: Pre-populate the AntiSpoof extension's table
  command: chdir={{ WIKIDIR }} php extensions/AntiSpoof/maintenance/batchAntiSpoof.php

- name: Create MediaWiki users
  command: chdir={{ROOTDIR}} bash "{{SCRIPTDIR}}/create_users.sh"

- name: Import Semantic templates and other MediaWiki special pages
  command: chdir={{ROOTDIR}} bash "{{SCRIPTDIR}}/import_pages.sh"

- name: Install parsoid
  command: chdir={{ROOTDIR}} bash "{{SCRIPTDIR}}/install_parsoid.sh"

...
