# Variables for ansible provisioning
#  https://docs.ansible.com/ansible/latest/playbooks_variables.html

env: "dev"
#apt_proxy: IP address # Install apt-cacher-ng on the host to avoid downloading packages again.

vagrant:
  private_network_ip: "192.168.33.10" # Sets IP address for the Virtual Machine
  hostname: "hitchwiki.test" # Hostname to use for the development server
  hostmanager_enabled: True  # Set `false` to use only private network IP to access the server.
                             # Vagrant won't therefore modify your `/etc/hosts` file neither.
db:
  server: mariadb
  host: localhost
  username: root
  password: root
  database: hitchwiki_en
  prefix:
  phpmyadmin_password: autobahn
# TODO use vault
db_credentials: "-u {{ db.username }} -p{{ db.password }}"

apache:
  user: www-data
  group: www-data

mediawiki:
  debug: False
  cache: False
  branch: REL1_29
  owner: "{{ apache.user }}:{{ apache.group }}"
  sitename: Hitchwiki
  metanamespace: Hitchwiki
  domain: hitchwiki.test
  cookiedomain: .hitchwiki.test
  protocol: http # change to https with enabled TLS
  visible_to_search_engines: True
  user:
    Hitchwiki: "{{ db.phpmyadmin_password }}"
    Hitchbot: "{{ db.phpmyadmin_password }}"
    Hitchhiker: "{{ db.phpmyadmin_password }}"
  smtp: # MailDev is running at port 1025 at dev server https://github.com/djfarrelly/MailDev
    enabled: true # See http://hitchwiki.test:1080/
    host: localhost
    port: 1025
    auth: false # Should we use SMTP authentication (true or false)
    username:
    password:
  spam: # https://www.google.com/recaptcha/intro/index.html
    spamprotection: False
    # These keys will work only at domains hitchwiki.test and 192.168.33.10
    # TODO use vault https://docs.ansible.com/ansible/latest/playbooks_vault.html
    recaptchapublickey: 6Lfx_-cSAAAAAFNMDH9fuFc37x_TYkOAcYHY_ZNc
    recaptchaprivatekey: 6Lfx_-cSAAAAAAdawoKHU7z83VS3aEJETODcCLQf
  mapbox: # MapBox (access token: the public one!)
    username: trustroots    
    access_token: pk.eyJ1IjoidHJ1c3Ryb290cyIsImEiOiJVWFFGa19BIn0.4e59q4-7e8yvgvcd1jzF4g
    mapkey_streets: ce8bb774
    mapkey_satellite: kil7hee6
  geonames:
    username: hitchwiki
    # use these instead of the above if geonames requests are being throttled
    # during migration. keep this list in the end of the file, as "[]" causes
    # bash_ini_parser to crash (we don't need these variables in bash)
    alternatives: { hitchwiki, hitchwiki2, hitchwiki3 }
