# Variables for ansible provisioning
# See https://docs.ansible.com/ansible/latest/playbooks_variables.html

# TODO make this dynamic
env: "dev"
ssl: False
debug: False
cache: False

dir:
  root: 	/var/www
  conf: 	"{{dir.root}}/configs"
  script: 	"{{dir.root}}/scripts"
  pages: 	"{{dir.script}}/pages"
  settings: 	"{{dir.conf}}/settings.yml"
  wikifolder:	wiki # TODO do we need this to be dynamic?
  wiki: 	"{{dir.root}}/public/{{dir.wikifolder}}"
  mwconf: 	"{{dir.root}}/mediawiki.php"
  dumps: 	"{{dir.root}}/dumps"
  phpmyadmin:	/usr/share/phpmyadmin

db:
  server: mariadb
  host: localhost
  username: root
  password: root
  database: hitchwiki_en
  prefix:
  phpmyadmin_password: autobahn

hw:
  branch:		REL1_29
  owner:		"{{webserver_user}}:{{webserver_group}}"
  sitename:		Hitchwiki
  metanamespace:	Hitchwiki
  domain:		hitchwiki.test
  cookiedomain:		.hitchwiki.test
  protocol:		http # change to https with enabled TLS

# Apache
webserver_user: www-data
webserver_group: www-data


# MailDev is running at port 1025 at dev server
# https://github.com/djfarrelly/MailDev
# See http://hitchwiki.test:1080/
smtp:
  enabled: true
  host: localhost
  port: 1025
# Should we use SMTP authentication (true or false):
  auth: false
  username:
  password:

spam:
  spamprotection: false
# https://www.google.com/recaptcha/intro/index.html
# These keys will work only at domains hitchwiki.test and 192.168.33.10
# TODO use vault https://docs.ansible.com/ansible/latest/playbooks_vault.html
  recaptchapublickey: 6Lfx_-cSAAAAAFNMDH9fuFc37x_TYkOAcYHY_ZNc
  recaptchaprivatekey: 6Lfx_-cSAAAAAAdawoKHU7z83VS3aEJETODcCLQf

# vendor
mapbox:
  username: trustroots
  # MapBox (access token: the public one!)
  access_token: pk.eyJ1IjoidHJ1c3Ryb290cyIsImEiOiJVWFFGa19BIn0.4e59q4-7e8yvgvcd1jzF4g
  mapkey_streets: ce8bb774
  mapkey_satellite: kil7hee6

# Geonames
geonames_username: hitchwiki
# use these instead of the above if geonames requests are being throttled
# during migration. keep this list in the end of the file, as "[]" causes
# bash_ini_parser to crash (we don't need these variables in bash)
geonames_usernames:
  0: hitchwiki
  1: hitchwiki2
  2: hitchwiki3

# DEPRECATED TODO replace with above names if you find them to be referenced somewhere
ROOTDIR:	"{{dir.root}}"
CONFDIR:	"{{dir.conf}}"
SCRIPTDIR:	"{{dir.script}}"
PAGESDIR:	"{{dir.pages}}"
SETTINGSFILE:	"{{dir.settings}}"
WIKIFOLDER:	"{{dir.wikifolder}}"
WIKIDIR:	"{{dir.wiki}}"
MWCONFFILE:	"{{dir.mwconf}}"
DUMPSDIR:	"{{dir.dumps}}"
PHPMYADMINDIR:	"{{dir.phpmyadmin}}"
hw_owners: "{{hw.owner}}"
HW__general__sitename: "{{hw.sitename}}"
HW__general__metanamespace: "{{hw.metanamespace}}"
HW__general__domain: "{{hw.domain}}"
protocol: "{{hw.protocol}}"
cookiedomain: "{{hw.cookiedomain}}"
