---

# Sets IP for the Virtual Machine
private_network_ip: "192.168.33.10"

# Hostname to use for the development server
#
# If you modify this, remember to change `domain` value from `settings.ini`
hostname: "hitchwiki.test"

# Setup server using self signed SSL certificate
#
# When `true`: remember to set `protocol` to `https` from `configs/settings.ini`
setup_ssl: false

# Set `false` to use only private network IP to access the server.
# Vagrant won't therefore modify your `/etc/hosts` file neither.
#
# When `false`: remember to change domain to private network IP from `configs/settings.ini`
hostmanager_enabled: true
