---
# Bring up apache2 webserver with PHP7 and extensions

# Examples:
#   https://github.com/ansible/ansible-examples/tree/master/lamp_simple
#   https://github.com/ansible/ansible-examples/blob/master/wordpress-nginx/roles/php-fpm/tasks/main.yml

- name: Install Apache2 with PHP7 and extensions
  become: yes
  apt: name={{ item }} state=present
  with_items: "{{ pkg.web }}"

- name: Enable apache mod rewrite
  become: yes
  apache2_module: name=rewrite state=present
  notify: restart apache

- name: Allow apache override to all
  become: yes
  replace:
    path: /etc/apache2/apache2.conf
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
    validate: '/usr/sbin/apache2ctl -f %s -t'
  notify: restart apache

- name: Remove default Apache2 site
  become: yes
  file: state=absent path=/etc/apache2/sites-enabled/000-default.conf
  notify: restart apache

- name: Remove default Apache2 webroot
  file: state=absent path={{ROOTDIR}}/html
  notify: restart apache

- name: Configure Hitchwiki for Apache2
  become: yes
  file: state=link src={{CONFDIR}}/apache-hitchwiki.conf path=/etc/apache2/sites-available/hitchwiki.conf force=yes
  notify: restart apache

- name: Activate Hitchwiki in Apache2
  become: yes
  file: state=link src=/etc/apache2/sites-available/hitchwiki.conf path=/etc/apache2/sites-available/hitchwiki.conf force=yes
  notify: restart apache

# NodeSource (https://nodejs.org/en/download/package-manager)
- name: Install NodeSoure 8.x
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  # TODO migrate the bash script here

- name: Finish web tasks
  lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_web_tasks'
    line: 'finished_web_tasks: True'

...
