---
# Common tasks

- name: 'install python2' # Ansible needs python or it fails with "/usr/bin/python: not found"
  become: yes
  apt: name=python-simplejson state=present
  # See https://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found

- name: Are variables loaded?
  command: "echo {{ private_network_ip }} {{ hostname }} {{ dir.conf }}"

- name: Set language
  lineinfile: 
    path: .profile
    line: |
      export LC_ALL="en_US.UTF-8"
      export LANGUAGE="en_US.UTF-8"

- name: Make sure settings.yml exists
  copy: src=configs/settings-example.yml dest=/var/www/configs/settings.yml force=no

- name: Use apt-cacher
  lineinfile:
    path: /etc/apt/apt.conf.d/apt-cacher-ng
    regexp: '^Acquire::http::Proxy'
    line: >
      Acquire::http::Proxy "http://{{ apt_proxy }}:3142/";
      Acquire::https::Proxy "false"; # or enable "PassThroughPattern: .*" in /etc/apt-cacher-ng/acng.conf
      # See https://blog.packagecloud.io/eng/2015/05/05/using-apt-cacher-ng-with-ssl-tls/
  when: apt_proxy is defined

# Start long downloads in background
# See: http://www.linuxnix.com/ansible-run-commands-in-background-in-playbooks
- name: install helper tools
  become: true
  at: command="apt-get install {{ pkg.helper }}, {{ pkg.db }}, {{ pkg.web }}, {{ pkg.mw }}" count=1 units=minutes
  #notify: update system

- name: Install mediawiki
  at: command='cd {{ dir.root }} && composer install --no-dev --no-autoloader -vv 2>&1 |tee -a composer.log' count=1 units=minutes

- name: Install shyaml to parse yml files
  at: command="pip install shyaml" count=1 units=minutes
  #pip: name=shyaml state=present

- name: Finish common tasks
  lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_common_tasks'
    line: 'finished_common_tasks: True'

...
