---

- name: Make sure settings.ini exists
  # TODO replace this by settings.yml
  copy: path={{dir.settings}} src={{db.conf}}/settings-example.yml
  ignore_errors: True

- msg: Please copy 'configs/settings-example.yml' to 'configs/settings.yml'.
  when: result|failed

- name: Set language
  lineinfile: 
    path: .profile
    line: |
      export LC_ALL="en_US.UTF-8"
      export LANGUAGE="en_US.UTF-8"

- name: Update system
  become: true
  apt: update_cache=yes upgrade=dist #autoremove=yes autoclean=yes

- name: install helper tools
  become: true
  apt: package={{ item }} state=latest
  with_items: { unattended-upgrades, vim, curl, git, unzip, zip, imagemagick, build-essential, python-software-properties, fail2ban }

...
