---
# Devlopment specific tasks

# Maildev
- name: Install PHP PEAR modules
  become: true
  pear: name={{item}} state=present
  with_items: { Auth_SASL, mail, mail_mime, Net_SMTP }

- name: Install Maildev for catching emails while developing
  become: true
  npm: name=maildev version=1.0.0-rc3 state=present global=yes
  notify: restart maildev

- name: Setup Maildev to start on reboot
  become: true
  file: state=link src={{SCRIPTDIR}}/init_maildev.sh path=/etc/init.d/maildev mode='755' force=yes

- name: Create Maildev startup symlink
  become: true
  file: state=link src=/etc/init.d/maildev path=/etc/rc3.d/S99maildev force=yes

# MariaDB
- name: Save db credentials locally
  # See https://dev.mysql.com/doc/refman/5.7/en/option-files.html
  copy:
    dest: ~/.my.cnf
    content: |
      [client]
      user={{db.username}}
      password={{db.password}}

- import_tasks: roles/db/tasks/main.yml
  when: not finished_db_tasks

- name: Configure MariaDB not to prompt for passwords
  become: true
  # https://docs.ansible.com/ansible/latest/mysql_db_module.html
  # Both login_password and login_user are required when you are passing credentials.
  # If none are present, the module will attempt to read the credentials from ~/.my.cnf,
  # and finally fall back to using the MySQL default login of ‘root’ with no password.
  shell: |
    debconf-set-selections <<< "mariadb-server-10.2 mysql-server/root_password password" {{db.password}}
    debconf-set-selections <<< "mariadb-server-10.2 mysql-server/root_password_again password" {{db.password}}

# PHP debug
# https://github.com/Hitchwiki/hitchwiki/blob/master/configs/mediawiki.php#L59-L63
- name: Turn on PHP error reporting
  become: true
  lineinfile:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^error_reporting = .*'
    line: 'error_reporting = E_ALL'
  when: debug
  notify: restart apache

- name: Display PHP errors
  become: true
  lineinfile:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^display_errors = .*'
    line: 'display_errors = On'
  when: debug
  notify: restart apache

- name: Turn off PHP error reporting
  become: true
  lineinfile:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^error_reporting = E_ALL'
    line: 'error_reporting = .*'
  when: not debug
  notify: restart apache

- name: Hide PHP errors
  become: true
  lineinfile:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^display_errors = On'
    line: 'display_errors = .*'
  when: not debug
  notify: restart apache

# PHPMyAdmin
- import_tasks: roles/web/tasks/main.yml
  when: not finished_web_tasks
- name: Configure PHPMyAdmin
  become: true
  # TODO maybe use https://docs.ansible.com/ansible/latest/dpkg_selections_module.html
  # TODO Is it necessary to run this before the installation of the phpmyadmin package?
  shell: |
    debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-user string {{db.username}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password {{db.password}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password {{db.phpmyadmin_password}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password {{db.phpmyadmin_password}}"
  notify: restart apache

- name: Add PHPMyAdmin configuration to Apache
  become: true
  lineinfile:
    path: /etc/phpmyadmin/apache.conf
    regexp: '(Alias /).*(/usr/share/phpmyadmin)'
    line: '\1{{PHPMYADMIN_DIR}} \2'
  notify: restart apache

- name: Finish installation
  lineinfile:
    path: "{{ dir.settings }}"
    regexp: '^finished_installation'
    line: 'finished_installation: True'
  when: finished_common_tasks and finished_db_tasks and finished_web_tasks and finished_mw_tasks
  notify: status

...
