---
# Devlopment specific tasks

# Maildev

#- name: Install pear
#  become: true
#  apt: name=php-pear state=present
#- name: Install npm
#  become: true
#  apt: name=npm state=present
#- name: Install MySQL-python
#  become: yes
#  apt: name=python-mysqldb state=present
#- name: Install PHPMyAdmin
#  become: true
#  apt: package=phpmyadmin state=present

- name: Install PHP PEAR modules
  become: true
  pear: name={{item}} state=present
  with_items: { Auth_SASL, mail, mail_mime, Net_SMTP }
  # TODO Failed to find required executable pear in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  ignore_errors: yes

- name: Install Maildev for catching emails while developing
  become: true
  npm: name=maildev version=1.0.0-rc3 state=present global=yes
  notify: restart maildev

- name: Setup Maildev to start on reboot
  become: true
  file: state=link src=scripts/init_maildev.sh path=/etc/init.d/maildev mode='755' force=yes

- name: Create Maildev startup symlink
  become: true
  file: state=link src=/etc/init.d/maildev path=/etc/rc3.d/S99maildev

# MariaDB
- name: Create ~/.my.cnf
  # https://dev.mysql.com/doc/refman/5.7/en/option-files.html
  copy:
    dest: ~/.my.cnf
    content: |
      [client]
      user={{db.username}}
      password={{db.password}}

- name: Set MariaDB root user
  # TODO root necessary?
  become: true
  mysql_user: name={{db.username}} password={{db.password}} state=present
  notify: restart db

- name: Configure MariaDB installation not to prompt for passwords
  become: true
  # https://docs.ansible.com/ansible/latest/mysql_db_module.html
  # Both login_password and login_user are required when you are passing credentials.
  # If none are present, the module will attempt to read the credentials from ~/.my.cnf,
  # and finally fall back to using the MySQL default login of ‘root’ with no password.
  shell: |
    debconf-set-selections <<< "mariadb-server-10.2 mysql-server/root_password password" {{db.password}}
    debconf-set-selections <<< "mariadb-server-10.2 mysql-server/root_password_again password" {{db.password}}

# PHP debug
# https://github.com/Hitchwiki/hitchwiki/blob/master/configs/mediawiki.php#L59-L63
- name: Turn on PHP errors
  become: true
  shell: |
    sed -i "s/error_reporting = .*/error_reporting = E_ALL/" /etc/php/7.0/apache2/php.ini
    sed -i "s/display_errors = .*/display_errors = On/" /etc/php/7.0/apache2/php.ini
  when: debug
  notify: restart apache

# PHPMyAdmin
- name: Configure PHPMyAdmin
  become: true
  # TODO maybe use https://docs.ansible.com/ansible/latest/dpkg_selections_module.html
  shell: |
    debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-user string {{db.username}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password {{db.password}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password {{db.phpmyadmin_password}}"
    debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password {{db.phpmyadmin_password}}"
  # TODO Is it necessary to run this before the installation of the phpmyadmin package?
  notify: restart apache

- name: Add PHPMyAdmin configuration to Apache
  become: true
  command: sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf
  notify: restart apache

...
