---
# This play expects root access on a remote debian system (or derivate with present apt).
# It will create a hitchwiki user, checkout the repository and install ansible

# See INSTALL.md => Installing using vagrant
- hosts: hitchwiki
  gather_facts: no
  pre_tasks:
    - name: 'install python2' # Ansible needs python or it fails with "/usr/bin/python: not found"
      become: yes
      raw: sudo apt-get install -yq python-simplejson

- name: Deploy system
  hosts: hitchwiki
  roles:
    - deploy

- name: Setup hitchwiki
  hosts: hitchwiki
  remote_user: "{{ user }}"
  roles:
    - hitchwiki
    - update
    - status
...
