---
# This playbook is used to gather status updates from all guests in logs/status/{{ansible_host}} (see below)
#  - First scripts/status.sh is triggered remotely which writes to log/state.yml.
#  - Then a report with passed chapters and started services is shown for each host.
# When code/paths changed lately the update playbook should be run first to issue `git pull`.

- name: Hitchwiki installation report
  hosts: all
  gather_facts: no
  vars:
    from_remote: true # inform the client that a fetch is necessary
    dir:
      script: /var/www/scripts
      state: /var/www/logs/state.yml
      log: "{{ lookup('pipe', 'pwd') }}/../../logs" # from remote we need to override the global here non-existent /var/www/logs
    chapters:
    services:
  roles:
    - status

...
