---
# This helper role
# - execute `scripts/status.sh` to print a status report on stdout that can be shown in ansible.
# - logs the state of the environment to `scripts/ansible/.state.yml`
# - loads `.state.yml`
# - prints a message when everything is finished

# If you include this role at the beginning of your book, you can inspect it with
#- debug:
#    var: state

- hosts: all
  gather_facts: no
  vars_files:
    - configs/settings.yml
  pre_tasks:
    - name: Update status
      command: "{{ dir.script }}/status.sh"
    - name: Retrieve summary
      fetch: src={{ dir.state }} dest=status/{{ ansible_host }}/ flat=yes
    - name: Load summary
      include_vars: "status/{{ ansible_host }}/state.yml"

- name: Show summary
  hosts: all
  vars:
    no_outro: true
  gather_facts: no
  roles:
    - status

...
